"""initial_schema

Revision ID: 2142e10de002
Revises: 
Create Date: 2025-12-30 13:36:21.511061

"""
from alembic import op
import sqlalchemy as sa


revision = '2142e10de002'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_price_currency', sa.String(length=3), nullable=False),
    sa.Column('paid_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('special_note', sa.String(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_receipt_id'), 'advance_receipt', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_for', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('status_changed_by', sa.Integer(), nullable=True),
    sa.Column('next_approval_group', sa.String(length=255), nullable=True),
    sa.Column('next_user_to_approve', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_auth_group_id'), 'auth_group', ['id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_auth_permission_id'), 'auth_permission', ['id'], unique=False)
    op.create_table('bank_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposits_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_for', sa.Text(), nullable=True),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_deposits_id'), 'bank_deposits', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('contact_number', sa.String(length=255), nullable=True),
    sa.Column('branch_code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_code'),
    sa.UniqueConstraint('branch_name')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('ref_number', sa.String(length=30), nullable=True),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.Column('deposited', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_payments_id'), 'card_payments', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('cheque_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheque_number', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=False),
    sa.Column('from', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('payment_for', sa.Text(), nullable=True),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheque_payments_id'), 'cheque_payments', ['id'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso_numeric', sa.Integer(), nullable=False),
    sa.Column('fips', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('area', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('continent', sa.String(length=2), nullable=True),
    sa.Column('tld', sa.String(length=255), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('currency_symbol', sa.String(length=255), nullable=True),
    sa.Column('currency_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('postal_code_format', sa.String(length=255), nullable=True),
    sa.Column('postal_code_regex', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('geonameid', sa.Integer(), nullable=True),
    sa.Column('neighbours', sa.String(length=255), nullable=True),
    sa.Column('equivalent_fips_code', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_table('credit_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_payments_id'), 'credit_payments', ['id'], unique=False)
    op.create_table('customer_gift_voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('barcode_no', sa.Integer(), nullable=False),
    sa.Column('valid_period_in_months', sa.Integer(), nullable=False),
    sa.Column('claimed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('purchased_invoice_no', sa.String(length=200), nullable=True),
    sa.Column('claimed_invoice_no', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_gift_voucher_id'), 'customer_gift_voucher', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expenses_no', sa.String(length=200), nullable=False),
    sa.Column('expenses_method', sa.String(length=30), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('bill_reference', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('good_received_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_good_received_locations_id'), 'good_received_locations', ['id'], unique=False)
    op.create_table('items_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_brand_id'), 'items_brand', ['id'], unique=False)
    op.create_table('supplier_credits_settle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_credits_settle_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('suppliers_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_credits_settle_id'), 'supplier_credits_settle', ['id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('name_in_cheque_card', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('payment_address', sa.Text(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('id_card_number', sa.String(length=12), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('civil_status', sa.String(length=30), nullable=False),
    sa.Column('passport_no', sa.String(length=50), nullable=True),
    sa.Column('no_of_kids', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('home_contact_number', sa.String(length=12), nullable=True),
    sa.Column('mobile_contact_number', sa.String(length=12), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('max_credit_limit', sa.Integer(), nullable=False),
    sa.Column('left_credit_amount', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('initial_credit_amount', sa.Integer(), nullable=True),
    sa.Column('is_customer_agent', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('item_transfer_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_transfer_note', sa.String(length=355), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['good_received_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_transfer_note')
    )
    op.create_index(op.f('ix_item_transfer_note_id'), 'item_transfer_note', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_code', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_active', sa.Boolean(), nullable=False),
    sa.Column('website_price', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('items_brand_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['items_brand_id'], ['items_brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name_in_cheque_card', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_registration_number', sa.String(length=255), nullable=True),
    sa.Column('company_postal_address', sa.Text(), nullable=True),
    sa.Column('company_contact_number', sa.String(length=12), nullable=True),
    sa.Column('company_website', sa.String(length=200), nullable=True),
    sa.Column('postal_address', sa.Text(), nullable=False),
    sa.Column('permenent_address', sa.Text(), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('id_card_number', sa.String(length=12), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('civil_status', sa.String(length=30), nullable=False),
    sa.Column('passport_no', sa.String(length=50), nullable=True),
    sa.Column('no_of_kids', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('home_contact_number', sa.String(length=12), nullable=True),
    sa.Column('mobile_contact_number', sa.String(length=12), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('max_credit_limit', sa.Integer(), nullable=False),
    sa.Column('left_credit_amount', sa.Integer(), nullable=True),
    sa.Column('initial_credit_amount', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('verify', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('occupation', sa.String(length=30), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('profile_picture_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('accounts_user_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branches_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branches_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_user_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inventory_no', sa.Text(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('asigned_to', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_assets_id'), 'company_assets', ['id'], unique=False)
    op.create_table('customer_advance_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_payments_no', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advance_payments_no')
    )
    op.create_index(op.f('ix_customer_advance_payments_id'), 'customer_advance_payments', ['id'], unique=False)
    op.create_table('customer_credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_credit_notes_id'), 'customer_credit_notes', ['id'], unique=False)
    op.create_table('customer_credits_settle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_credits_settle_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_credits_settle_no')
    )
    op.create_index(op.f('ix_customer_credits_settle_id'), 'customer_credits_settle', ['id'], unique=False)
    op.create_table('customer_cupon_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupon_code', sa.String(length=10), nullable=False),
    sa.Column('limit_by_usage', sa.Integer(), nullable=False),
    sa.Column('limit_for_customer', sa.Integer(), nullable=False),
    sa.Column('valid_until_date', sa.Date(), nullable=False),
    sa.Column('limit_validity_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['limit_validity_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_cupon_codes_id'), 'customer_cupon_codes', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('item_receive_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_transfer_note_id', sa.Integer(), nullable=False),
    sa.Column('received_approval_status', sa.SmallInteger(), nullable=False),
    sa.Column('received_note', sa.String(length=355), nullable=True),
    sa.Column('recieved_user', sa.Integer(), nullable=True),
    sa.Column('recieved_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_transfer_note_id'], ['item_transfer_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_receive_note_id'), 'item_receive_note', ['id'], unique=False)
    op.create_table('item_transfer_note_approved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_transfer_note_id', sa.Integer(), nullable=True),
    sa.Column('approved_status', sa.SmallInteger(), nullable=False),
    sa.Column('approval_note', sa.String(length=355), nullable=True),
    sa.Column('approved_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_transfer_note_id'], ['item_transfer_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_approved_id'), 'item_transfer_note_approved', ['id'], unique=False)
    op.create_table('item_transfer_note_item_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('itemtransfernote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemtransfernote_id'], ['item_transfer_note.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_item_product_id'), 'item_transfer_note_item_product', ['id'], unique=False)
    op.create_table('item_transfer_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('itemtransfernote_id', sa.Integer(), nullable=False),
    sa.Column('item_recieved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['itemtransfernote_id'], ['item_transfer_note.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_items_id'), 'item_transfer_note_items', ['id'], unique=False)
    op.create_table('minimum_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minimum_price_id'), 'minimum_price', ['id'], unique=False)
    op.create_table('purchasing_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchasing_order_no', sa.String(length=200), nullable=False),
    sa.Column('purchasing_invoice_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('purchasing_order_date', sa.Date(), nullable=False),
    sa.Column('good_received_note_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('credit_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('first_suppliers_id', sa.Integer(), nullable=False),
    sa.Column('second_suppliers_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['first_suppliers_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['second_suppliers_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_orders_id'), 'purchasing_orders', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weekday', sa.String(length=12), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('work_mins', sa.Integer(), nullable=False),
    sa.Column('ot_mins', sa.Integer(), nullable=False),
    sa.Column('full_attended_mins', sa.Integer(), nullable=False),
    sa.Column('late_mins', sa.Integer(), nullable=False),
    sa.Column('early_mins', sa.Integer(), nullable=False),
    sa.Column('absent_mins', sa.Integer(), nullable=False),
    sa.Column('leave_mins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('employee_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('add_1_name', sa.String(length=100), nullable=True),
    sa.Column('add_1_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_2_name', sa.String(length=100), nullable=True),
    sa.Column('add_2_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_sales_commision', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_salary_advance', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_reimbursements', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_epf_employee', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_etf_employee', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_stamp_duty', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_late_deductions', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('epf_employer', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('etf_employer', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_salary_advance_repayment', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_payroll_id'), 'employee_payroll', ['id'], unique=False)
    op.create_table('employee_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('appointed_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_promotions_id'), 'employee_promotions', ['id'], unique=False)
    op.create_table('employee_salary_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('add_1_name', sa.String(length=100), nullable=True),
    sa.Column('add_1_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_2_name', sa.String(length=100), nullable=True),
    sa.Column('add_2_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_salary_profile_id'), 'employee_salary_profile', ['id'], unique=False)
    op.create_table('employees_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('assign_reason', sa.Text(), nullable=True),
    sa.Column('revoke_assignment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['company_assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_assets_id'), 'employees_assets', ['id'], unique=False)
    op.create_table('good_received_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_received_no', sa.String(length=200), nullable=False),
    sa.Column('good_received_date', sa.Date(), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=200), nullable=False),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('good_received_locations_id', sa.Integer(), nullable=False),
    sa.Column('purchasingorders_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_locations_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['purchasingorders_id'], ['purchasing_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('good_received_no')
    )
    op.create_index(op.f('ix_good_received_note_id'), 'good_received_note', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sale_rep_id', sa.Integer(), nullable=False),
    sa.Column('customer_agent_id', sa.Integer(), nullable=True),
    sa.Column('approval', sa.Boolean(), nullable=False),
    sa.Column('customer_advance_payments_id', sa.Integer(), nullable=True),
    sa.Column('bank_transfer_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('card_amex_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('card_mastercard_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('card_visa_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('cheque_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('payment_adjustments', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('cupon_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('credit_note_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('special', sa.Boolean(), nullable=False),
    sa.Column('sys_code', sa.Integer(), nullable=True),
    sa.Column('created_date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('cheque_payment_id', sa.Integer(), nullable=True),
    sa.Column('bank_transfer_id', sa.Integer(), nullable=True),
    sa.Column('credit_payment_id', sa.Integer(), nullable=True),
    sa.Column('card_payment_id', sa.Integer(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('cupon_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['bank_transfer_id'], ['bank_deposits.id'], ),
    sa.ForeignKeyConstraint(['card_payment_id'], ['card_payments.id'], ),
    sa.ForeignKeyConstraint(['cheque_payment_id'], ['cheque_payments.id'], ),
    sa.ForeignKeyConstraint(['credit_note_id'], ['customer_credit_notes.id'], ),
    sa.ForeignKeyConstraint(['credit_payment_id'], ['credit_payments.id'], ),
    sa.ForeignKeyConstraint(['cupon_id'], ['customer_cupon_codes.id'], ),
    sa.ForeignKeyConstraint(['customer_advance_payments_id'], ['customer_advance_payments.id'], ),
    sa.ForeignKeyConstraint(['customer_agent_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_rep_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('leave_type', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('leave_reason', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('leave_duration', sa.Float(), nullable=False),
    sa.Column('leave_time', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_table('purchasing_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('warrenty_month', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchasingorders_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchasingorders_id'], ['purchasing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_order_items_id'), 'purchasing_order_items', ['id'], unique=False)
    op.create_table('reimbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('reimbursement_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('bill_image_path', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_reimbursements_id'), 'reimbursements', ['id'], unique=False)
    op.create_table('salary_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_deductions_id'), 'salary_deductions', ['id'], unique=False)
    op.create_table('customer_credits_settle_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('payment_method_number', sa.String(length=300), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('customer_credit_settle_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_credit_settle_id'], ['customer_credits_settle.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_credits_settle_transaction_id'), 'customer_credits_settle_transaction', ['id'], unique=False)
    op.create_table('customer_support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('assigned_user_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_support_id'), 'customer_support', ['id'], unique=False)
    op.create_table('good_received_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_received_note', sa.String(length=355), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('purchasing_order_items_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['purchasing_order_items_id'], ['purchasing_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_good_received_items_id'), 'good_received_items', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warrenty_month', sa.String(length=30), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_selling_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('purchasing_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchasing_return_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('goodreceivednote_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['goodreceivednote_id'], ['good_received_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_return_id'), 'purchasing_return', ['id'], unique=False)
    op.create_table('sale_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('good_received_locations_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['good_received_locations_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_return_no')
    )
    op.create_index(op.f('ix_sale_return_id'), 'sale_return', ['id'], unique=False)
    op.create_table('supplier_credits_settle_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('payment_method_number', sa.String(length=300), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('good_received_id', sa.Integer(), nullable=False),
    sa.Column('supplier_credit_settle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_received_id'], ['good_received_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_credits_settle_transaction_id'), 'supplier_credits_settle_transaction', ['id'], unique=False)
    op.create_table('warranty_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warranty_type', sa.String(length=30), nullable=False),
    sa.Column('warranty_status', sa.String(length=30), nullable=False),
    sa.Column('product_barcode_old_code', sa.String(length=255), nullable=False),
    sa.Column('product_barcode_new_code', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_warrenty_claims', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warranty_claims_id'), 'warranty_claims', ['id'], unique=False)
    op.create_table('cs_job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('job_status', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_support_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warrent_claim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_support_id'], ['customer_support.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warrent_claim_id'], ['warranty_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_job_item_id'), 'cs_job_item', ['id'], unique=False)
    op.create_table('customer_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('contact_person', sa.String(length=60), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_support_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_support_id'], ['customer_support.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_call_log_id'), 'customer_call_log', ['id'], unique=False)
    op.create_table('invoice_items_barcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('good_received_items_id', sa.Integer(), nullable=False),
    sa.Column('invoice_items_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_items_id'], ['good_received_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_items_id'], ['invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_barcode_id'), 'invoice_items_barcode', ['id'], unique=False)
    op.create_table('purchasing_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchasing_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('return_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchasingreturn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchasingreturn_id'], ['purchasing_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_return_items_id'), 'purchasing_return_items', ['id'], unique=False)
    op.create_table('sale_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('return_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sold_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_return_items_id'), 'sale_return_items', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_return_items_id'), table_name='sale_return_items')
    op.drop_table('sale_return_items')
    op.drop_index(op.f('ix_purchasing_return_items_id'), table_name='purchasing_return_items')
    op.drop_table('purchasing_return_items')
    op.drop_index(op.f('ix_invoice_items_barcode_id'), table_name='invoice_items_barcode')
    op.drop_table('invoice_items_barcode')
    op.drop_index(op.f('ix_customer_call_log_id'), table_name='customer_call_log')
    op.drop_table('customer_call_log')
    op.drop_index(op.f('ix_cs_job_item_id'), table_name='cs_job_item')
    op.drop_table('cs_job_item')
    op.drop_index(op.f('ix_warranty_claims_id'), table_name='warranty_claims')
    op.drop_table('warranty_claims')
    op.drop_index(op.f('ix_supplier_credits_settle_transaction_id'), table_name='supplier_credits_settle_transaction')
    op.drop_table('supplier_credits_settle_transaction')
    op.drop_index(op.f('ix_sale_return_id'), table_name='sale_return')
    op.drop_table('sale_return')
    op.drop_index(op.f('ix_purchasing_return_id'), table_name='purchasing_return')
    op.drop_table('purchasing_return')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_good_received_items_id'), table_name='good_received_items')
    op.drop_table('good_received_items')
    op.drop_index(op.f('ix_customer_support_id'), table_name='customer_support')
    op.drop_table('customer_support')
    op.drop_index(op.f('ix_customer_credits_settle_transaction_id'), table_name='customer_credits_settle_transaction')
    op.drop_table('customer_credits_settle_transaction')
    op.drop_index(op.f('ix_salary_deductions_id'), table_name='salary_deductions')
    op.drop_table('salary_deductions')
    op.drop_index(op.f('ix_reimbursements_id'), table_name='reimbursements')
    op.drop_table('reimbursements')
    op.drop_index(op.f('ix_purchasing_order_items_id'), table_name='purchasing_order_items')
    op.drop_table('purchasing_order_items')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_good_received_note_id'), table_name='good_received_note')
    op.drop_table('good_received_note')
    op.drop_index(op.f('ix_employees_assets_id'), table_name='employees_assets')
    op.drop_table('employees_assets')
    op.drop_index(op.f('ix_employee_salary_profile_id'), table_name='employee_salary_profile')
    op.drop_table('employee_salary_profile')
    op.drop_index(op.f('ix_employee_promotions_id'), table_name='employee_promotions')
    op.drop_table('employee_promotions')
    op.drop_index(op.f('ix_employee_payroll_id'), table_name='employee_payroll')
    op.drop_table('employee_payroll')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_purchasing_orders_id'), table_name='purchasing_orders')
    op.drop_table('purchasing_orders')
    op.drop_index(op.f('ix_minimum_price_id'), table_name='minimum_price')
    op.drop_table('minimum_price')
    op.drop_index(op.f('ix_item_transfer_note_items_id'), table_name='item_transfer_note_items')
    op.drop_table('item_transfer_note_items')
    op.drop_index(op.f('ix_item_transfer_note_item_product_id'), table_name='item_transfer_note_item_product')
    op.drop_table('item_transfer_note_item_product')
    op.drop_index(op.f('ix_item_transfer_note_approved_id'), table_name='item_transfer_note_approved')
    op.drop_table('item_transfer_note_approved')
    op.drop_index(op.f('ix_item_receive_note_id'), table_name='item_receive_note')
    op.drop_table('item_receive_note')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customer_cupon_codes_id'), table_name='customer_cupon_codes')
    op.drop_table('customer_cupon_codes')
    op.drop_index(op.f('ix_customer_credits_settle_id'), table_name='customer_credits_settle')
    op.drop_table('customer_credits_settle')
    op.drop_index(op.f('ix_customer_credit_notes_id'), table_name='customer_credit_notes')
    op.drop_table('customer_credit_notes')
    op.drop_index(op.f('ix_customer_advance_payments_id'), table_name='customer_advance_payments')
    op.drop_table('customer_advance_payments')
    op.drop_index(op.f('ix_company_assets_id'), table_name='company_assets')
    op.drop_table('company_assets')
    op.drop_table('accounts_user_user_permissions')
    op.drop_table('accounts_user_groups')
    op.drop_table('accounts_user_branches')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_item_transfer_note_id'), table_name='item_transfer_note')
    op.drop_table('item_transfer_note')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_supplier_credits_settle_id'), table_name='supplier_credits_settle')
    op.drop_table('supplier_credits_settle')
    op.drop_index(op.f('ix_items_brand_id'), table_name='items_brand')
    op.drop_table('items_brand')
    op.drop_index(op.f('ix_good_received_locations_id'), table_name='good_received_locations')
    op.drop_table('good_received_locations')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customer_gift_voucher_id'), table_name='customer_gift_voucher')
    op.drop_table('customer_gift_voucher')
    op.drop_index(op.f('ix_credit_payments_id'), table_name='credit_payments')
    op.drop_table('credit_payments')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_cheque_payments_id'), table_name='cheque_payments')
    op.drop_table('cheque_payments')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_card_payments_id'), table_name='card_payments')
    op.drop_table('card_payments')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_bank_deposits_id'), table_name='bank_deposits')
    op.drop_table('bank_deposits')
    op.drop_index(op.f('ix_auth_permission_id'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('ix_auth_group_id'), table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_advance_receipt_id'), table_name='advance_receipt')
    op.drop_table('advance_receipt')
    # ### end Alembic commands ###
