"""add_created_by_to_invoices

Revision ID: 2d3a3f0d6240
Revises: 20260429_tax_norm
Create Date: 2026-04-30 00:29:47.689998

"""
from alembic import op
import sqlalchemy as sa

revision = '2d3a3f0d6240'
down_revision = '20260429_tax_norm'
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.add_column('invoices', sa.Column('created_by', sa.Integer(), sa.ForeignKey('accounts_user.id'), nullable=True))

def downgrade() -> None:
    op.drop_column('invoices', 'created_by')

def _upgrade_old() -> None:
    pass  # old autogenerated body below (preserved for reference, not executed)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sdn_supplier_status'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_branch_code'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_debit_note_no'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_purchasing_order_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_status'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_supplier_id'), table_name='supplier_debit_notes')
    op.drop_table('supplier_debit_notes')
    op.drop_index(op.f('ix_sdn_settlements_applied_to_po_id'), table_name='supplier_debit_note_settlements')
    op.drop_index(op.f('ix_sdn_settlements_debit_note_id'), table_name='supplier_debit_note_settlements')
    op.drop_table('supplier_debit_note_settlements')
    op.drop_index(op.f('ix_accounting_periods_year'), table_name='accounting_periods')
    op.create_index(op.f('ix_accounting_periods_id'), 'accounting_periods', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_bank_deposits_branch'), table_name='bank_deposits')
    op.drop_constraint(op.f('cash_flow_categories_category_code_key'), 'cash_flow_categories', type_='unique')
    op.create_index(op.f('ix_cash_flow_categories_category_code'), 'cash_flow_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_cash_flow_categories_id'), 'cash_flow_categories', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statement_lines_id'), 'cash_flow_statement_lines', ['id'], unique=False)
    op.drop_constraint(op.f('cash_flow_statements_statement_no_key'), 'cash_flow_statements', type_='unique')
    op.create_index(op.f('ix_cash_flow_statements_id'), 'cash_flow_statements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_statement_no'), 'cash_flow_statements', ['statement_no'], unique=True)
    op.drop_constraint(op.f('chart_of_accounts_account_code_key'), 'chart_of_accounts', type_='unique')
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_account_code'), 'chart_of_accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_cheque_payments_branch'), table_name='cheque_payments')
    op.drop_index(op.f('ix_company_assets_branch'), table_name='company_assets')
    op.drop_index(op.f('ix_company_assets_grn'), table_name='company_assets')
    op.drop_index(op.f('ix_coupon_usage_coupon'), table_name='coupon_usage')
    op.drop_index(op.f('ix_coupon_usage_customer'), table_name='coupon_usage')
    op.drop_index(op.f('ix_cs_job_item_ticket'), table_name='cs_job_item')
    op.drop_index(op.f('ix_cacpi_commission_id'), table_name='customer_agent_commission_payment_items')
    op.drop_index(op.f('ix_cacpi_payment_id'), table_name='customer_agent_commission_payment_items')
    op.drop_index(op.f('ix_cacp_agent_id'), table_name='customer_agent_commission_payments')
    op.drop_index(op.f('ix_cacp_status'), table_name='customer_agent_commission_payments')
    op.drop_index(op.f('ix_cac_agent_id'), table_name='customer_agent_commissions')
    op.drop_index(op.f('ix_cac_invoice_id'), table_name='customer_agent_commissions')
    op.drop_index(op.f('ix_cac_status'), table_name='customer_agent_commissions')
    op.drop_index(op.f('ix_customer_call_log_ticket'), table_name='customer_call_log')
    op.drop_index(op.f('ix_customer_credit_notes_customer'), table_name='customer_credit_notes')
    op.drop_index(op.f('ix_customer_support_assigned'), table_name='customer_support')
    op.drop_index(op.f('ix_customer_support_branch'), table_name='customer_support')
    op.drop_index(op.f('ix_customer_support_customer'), table_name='customer_support')
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.drop_index(op.f('ix_employee_payroll_batch_no'), table_name='employee_payroll')
    op.drop_index(op.f('ix_employee_payroll_employee'), table_name='employee_payroll')
    op.create_index(op.f('ix_employee_payroll_payroll_batch_no'), 'employee_payroll', ['payroll_batch_no'], unique=False)
    op.drop_column('employee_payroll', 'add_sales_commission')
    op.drop_index(op.f('ix_employee_promotions_employee'), table_name='employee_promotions')
    op.drop_index(op.f('ix_employee_salary_profile_employee'), table_name='employee_salary_profile')
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'operational'::character varying"))
    op.alter_column('expenses', 'expense_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'miscellaneous'::character varying"))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_expenses_branch_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_date'), table_name='expenses')
    op.create_unique_constraint(None, 'expenses', ['expenses_no'])
    op.create_index(op.f('ix_general_ledger_id'), 'general_ledger', ['id'], unique=False)
    op.drop_index(op.f('ix_good_received_items_grn'), table_name='good_received_items')
    op.drop_index(op.f('ix_good_received_note_branch'), table_name='good_received_note')
    op.drop_index(op.f('ix_good_received_note_po'), table_name='good_received_note')
    op.create_index(op.f('ix_good_received_note_branch_code'), 'good_received_note', ['branch_code'], unique=False)
    op.create_index(op.f('ix_invoice_card_payments_invoice_id'), 'invoice_card_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_card_payments_payment_card_id'), 'invoice_card_payments', ['payment_card_id'], unique=False)
    op.drop_index(op.f('ix_invoice_items_invoice'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_product'), table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.add_column('invoices', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('invoices_invoice_no_key'), 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_customer'), table_name='invoices')
    op.create_index(op.f('ix_invoices_approval_status'), 'invoices', ['approval_status'], unique=False)
    op.create_index(op.f('ix_invoices_branch_code'), 'invoices', ['branch_code'], unique=False)
    op.create_index(op.f('ix_invoices_created_date'), 'invoices', ['created_date'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_payment_status'), 'invoices', ['payment_status'], unique=False)
    op.create_foreign_key(None, 'invoices', 'accounts_user', ['created_by'], ['id'])
    op.drop_index(op.f('ix_itn_branch_status'), table_name='item_transfer_note')
    op.drop_index(op.f('ix_itn_items_itn'), table_name='item_transfer_note_items')
    op.drop_index(op.f('ix_itn_items_product'), table_name='item_transfer_note_items')
    op.drop_index(op.f('ix_journal_entries_branch_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_no'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_constraint(op.f('journal_entries_journal_entry_no_key'), 'journal_entries', type_='unique')
    op.drop_index(op.f('uq_je_reference'), table_name='journal_entries', postgresql_where='((reference_type IS NOT NULL) AND (reference_id IS NOT NULL))')
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_journal_entry_no'), 'journal_entries', ['journal_entry_no'], unique=True)
    op.drop_column('journal_entries', 'reference_id')
    op.drop_column('journal_entries', 'reference_type')
    op.drop_index(op.f('ix_je_lines_account'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_je_lines_entry'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_je'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.drop_index(op.f('ix_leaves_employee'), table_name='leaves')
    op.drop_index(op.f('ix_monthly_sales_branch_period'), table_name='monthly_branch_sales_summary')
    op.create_index('idx_mbs_branch_period', 'monthly_branch_sales_summary', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.drop_index(op.f('ix_payroll_batches_status'), table_name='payroll_batches')
    op.create_index(op.f('ix_payroll_batches_id'), 'payroll_batches', ['id'], unique=False)
    op.alter_column('petty_cash', 'petty_cash_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('petty_cash', 'opening_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'current_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'opened_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('petty_cash', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_petty_cash_branch'), table_name='petty_cash')
    op.drop_index(op.f('ix_pct_fund_id'), table_name='petty_cash_transaction')
    op.drop_index(op.f('ix_pct_txn_date'), table_name='petty_cash_transaction')
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_items_brand_id'), 'products', ['items_brand_id'], unique=False)
    op.drop_index(op.f('ix_purchasing_order_items_po'), table_name='purchasing_order_items')
    op.drop_index(op.f('ix_purchasing_order_items_product'), table_name='purchasing_order_items')
    op.drop_index(op.f('ix_purchasing_orders_branch_status'), table_name='purchasing_orders')
    op.drop_index(op.f('ix_purchasing_orders_first_supplier'), table_name='purchasing_orders')
    op.drop_index(op.f('ix_purchasing_orders_second_supplier'), table_name='purchasing_orders')
    op.create_index(op.f('ix_purchasing_orders_branch_code'), 'purchasing_orders', ['branch_code'], unique=False)
    op.create_index(op.f('ix_purchasing_orders_status'), 'purchasing_orders', ['status'], unique=False)
    op.drop_index(op.f('ix_purchasing_return_branch_status'), table_name='purchasing_return')
    op.drop_index(op.f('ix_purchasing_return_grn'), table_name='purchasing_return')
    op.alter_column('reimbursement_items', 'receipt_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_reimbursement_items_reimbursement_id'), table_name='reimbursement_items')
    op.alter_column('reimbursements', 'reimbursement_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reimbursements', 'branch_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('reimbursements', 'claim_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('reimbursements', 'reimbursement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('reimbursements', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('reimbursements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reimbursements', 'verified_by',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('reimbursements', 'remark',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reimbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reimbursements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_reimbursements_status'), table_name='reimbursements')
    op.create_index(op.f('ix_reimbursements_employee_id'), 'reimbursements', ['employee_id'], unique=False)
    op.drop_column('reimbursements', 'bill_date')
    op.drop_column('reimbursements', 'reimbursement_amount')
    op.drop_index(op.f('ix_salary_deductions_employee'), table_name='salary_deductions')
    op.drop_index(op.f('ix_sale_return_branch'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_invoice'), table_name='sale_return')
    op.create_index(op.f('ix_sale_return_added_date'), 'sale_return', ['added_date'], unique=False)
    op.create_index(op.f('ix_sale_return_branch_code'), 'sale_return', ['branch_code'], unique=False)
    op.create_index(op.f('ix_sale_return_invoice_id'), 'sale_return', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sale_return_status'), 'sale_return', ['status'], unique=False)
    op.alter_column('sales_officer_monthly_commissions', 'commission_percentage',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_sales_commission_employee'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_period'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_status'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_summary'), table_name='sales_officer_monthly_commissions')
    op.drop_constraint(op.f('sales_commission_employee_period_unique'), 'sales_officer_monthly_commissions', type_='unique')
    op.create_index('idx_sales_comm_branch', 'sales_officer_monthly_commissions', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_index('idx_sales_comm_employee', 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_unique_constraint('sales_commission_unique', 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'])
    op.drop_constraint(op.f('sales_officer_monthly_commissions_monthly_sales_summary_id_fkey'), 'sales_officer_monthly_commissions', type_='foreignkey')
    op.drop_constraint(op.f('sales_officer_monthly_commissions_paid_in_payroll_id_fkey'), 'sales_officer_monthly_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'sales_officer_monthly_commissions', 'monthly_branch_sales_summary', ['monthly_sales_summary_id'], ['id'])
    op.create_foreign_key(None, 'sales_officer_monthly_commissions', 'employee_payroll', ['paid_in_payroll_id'], ['id'])
    op.drop_index(op.f('ix_sales_stock_branch'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_grn'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_product'), table_name='sales_stock')
    op.create_index(op.f('ix_sales_stock_branch_code'), 'sales_stock', ['branch_code'], unique=False)
    op.create_index(op.f('ix_sales_stock_product_id'), 'sales_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_stock_status'), 'sales_stock', ['status'], unique=False)
    op.drop_index(op.f('ix_supplier_advance_payment_branch'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_supplier'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_payments_branch_status'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_po'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier'), table_name='supplier_payments')
    op.drop_index(op.f('ix_voucher_usage_voucher'), table_name='voucher_usage')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_voucher_usage_voucher'), 'voucher_usage', ['voucher_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_po'), 'supplier_payments', ['purchasing_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_branch_status'), 'supplier_payments', ['branch_code', 'status'], unique=False)
    op.create_index(op.f('ix_supplier_advance_payment_supplier'), 'supplier_advance_payment', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_advance_payment_branch'), 'supplier_advance_payment', ['branch_code'], unique=False)
    op.drop_index(op.f('ix_sales_stock_status'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_product_id'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_branch_code'), table_name='sales_stock')
    op.create_index(op.f('ix_sales_stock_product'), 'sales_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_stock_grn'), 'sales_stock', ['good_received_note_id'], unique=False)
    op.create_index(op.f('ix_sales_stock_branch'), 'sales_stock', ['branch_code'], unique=False)
    op.drop_constraint(None, 'sales_officer_monthly_commissions', type_='foreignkey')
    op.drop_constraint(None, 'sales_officer_monthly_commissions', type_='foreignkey')
    op.create_foreign_key(op.f('sales_officer_monthly_commissions_paid_in_payroll_id_fkey'), 'sales_officer_monthly_commissions', 'payroll_batches', ['paid_in_payroll_id'], ['id'])
    op.create_foreign_key(op.f('sales_officer_monthly_commissions_monthly_sales_summary_id_fkey'), 'sales_officer_monthly_commissions', 'monthly_branch_sales_summary', ['monthly_sales_summary_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sales_commission_unique', 'sales_officer_monthly_commissions', type_='unique')
    op.drop_index('idx_sales_comm_employee', table_name='sales_officer_monthly_commissions')
    op.drop_index('idx_sales_comm_branch', table_name='sales_officer_monthly_commissions')
    op.create_unique_constraint(op.f('sales_commission_employee_period_unique'), 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sales_commission_summary'), 'sales_officer_monthly_commissions', ['monthly_sales_summary_id'], unique=False)
    op.create_index(op.f('ix_sales_commission_status'), 'sales_officer_monthly_commissions', ['status'], unique=False)
    op.create_index(op.f('ix_sales_commission_period'), 'sales_officer_monthly_commissions', ['fiscal_year', 'fiscal_month'], unique=False)
    op.create_index(op.f('ix_sales_commission_employee'), 'sales_officer_monthly_commissions', ['employee_id'], unique=False)
    op.alter_column('sales_officer_monthly_commissions', 'commission_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_sale_return_status'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_invoice_id'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_branch_code'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_added_date'), table_name='sale_return')
    op.create_index(op.f('ix_sale_return_invoice'), 'sale_return', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sale_return_branch'), 'sale_return', ['branch_code'], unique=False)
    op.create_index(op.f('ix_salary_deductions_employee'), 'salary_deductions', ['employee_id'], unique=False)
    op.add_column('reimbursements', sa.Column('reimbursement_amount', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.add_column('reimbursements', sa.Column('bill_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reimbursements_employee_id'), table_name='reimbursements')
    op.create_index(op.f('ix_reimbursements_status'), 'reimbursements', ['status'], unique=False)
    op.alter_column('reimbursements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'remark',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reimbursements', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reimbursements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reimbursements', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('reimbursements', 'reimbursement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('reimbursements', 'claim_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'branch_code',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('reimbursements', 'reimbursement_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_reimbursement_items_reimbursement_id'), 'reimbursement_items', ['reimbursement_id'], unique=False)
    op.alter_column('reimbursement_items', 'receipt_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_purchasing_return_grn'), 'purchasing_return', ['goodreceivednote_id'], unique=False)
    op.create_index(op.f('ix_purchasing_return_branch_status'), 'purchasing_return', ['branch_code', 'status'], unique=False)
    op.drop_index(op.f('ix_purchasing_orders_status'), table_name='purchasing_orders')
    op.drop_index(op.f('ix_purchasing_orders_branch_code'), table_name='purchasing_orders')
    op.create_index(op.f('ix_purchasing_orders_second_supplier'), 'purchasing_orders', ['second_suppliers_id'], unique=False)
    op.create_index(op.f('ix_purchasing_orders_first_supplier'), 'purchasing_orders', ['first_suppliers_id'], unique=False)
    op.create_index(op.f('ix_purchasing_orders_branch_status'), 'purchasing_orders', ['branch_code', 'status'], unique=False)
    op.create_index(op.f('ix_purchasing_order_items_product'), 'purchasing_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchasing_order_items_po'), 'purchasing_order_items', ['purchasingorders_id'], unique=False)
    op.drop_index(op.f('ix_products_items_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.create_index(op.f('ix_pct_txn_date'), 'petty_cash_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_pct_fund_id'), 'petty_cash_transaction', ['petty_cash_id'], unique=False)
    op.create_index(op.f('ix_petty_cash_branch'), 'petty_cash', ['branch_code'], unique=False)
    op.alter_column('petty_cash', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('petty_cash', 'opened_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('petty_cash', 'current_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'opening_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'petty_cash_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_payroll_batches_id'), table_name='payroll_batches')
    op.create_index(op.f('ix_payroll_batches_status'), 'payroll_batches', ['status'], unique=False)
    op.drop_index('idx_mbs_branch_period', table_name='monthly_branch_sales_summary')
    op.create_index(op.f('ix_monthly_sales_branch_period'), 'monthly_branch_sales_summary', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_index(op.f('ix_leaves_employee'), 'leaves', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_je'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_account'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_je_lines_entry'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_je_lines_account'), 'journal_entry_lines', ['account_id'], unique=False)
    op.add_column('journal_entries', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('journal_entries', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_journal_entries_journal_entry_no'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.create_index(op.f('uq_je_reference'), 'journal_entries', ['reference_type', 'reference_id'], unique=True, postgresql_where='((reference_type IS NOT NULL) AND (reference_id IS NOT NULL))')
    op.create_unique_constraint(op.f('journal_entries_journal_entry_no_key'), 'journal_entries', ['journal_entry_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_index(op.f('ix_journal_entries_no'), 'journal_entries', ['journal_entry_no'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_branch_status'), 'journal_entries', ['branch_code', 'status'], unique=False)
    op.create_index(op.f('ix_itn_items_product'), 'item_transfer_note_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_itn_items_itn'), 'item_transfer_note_items', ['itemtransfernote_id'], unique=False)
    op.create_index(op.f('ix_itn_branch_status'), 'item_transfer_note', ['branch_code', 'status'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_payment_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_approval_status'), table_name='invoices')
    op.create_index(op.f('ix_invoices_customer'), 'invoices', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('invoices_invoice_no_key'), 'invoices', ['invoice_no'], postgresql_nulls_not_distinct=False)
    op.drop_column('invoices', 'created_by')
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_product'), 'invoice_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice'), 'invoice_items', ['invoice_id'], unique=False)
    op.drop_index(op.f('ix_invoice_card_payments_payment_card_id'), table_name='invoice_card_payments')
    op.drop_index(op.f('ix_invoice_card_payments_invoice_id'), table_name='invoice_card_payments')
    op.drop_index(op.f('ix_good_received_note_branch_code'), table_name='good_received_note')
    op.create_index(op.f('ix_good_received_note_po'), 'good_received_note', ['purchasingorders_id'], unique=False)
    op.create_index(op.f('ix_good_received_note_branch'), 'good_received_note', ['branch_code'], unique=False)
    op.create_index(op.f('ix_good_received_items_grn'), 'good_received_items', ['good_received_note'], unique=False)
    op.drop_index(op.f('ix_general_ledger_id'), table_name='general_ledger')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.create_index(op.f('ix_expenses_created_date'), 'expenses', ['created_date'], unique=False)
    op.create_index(op.f('ix_expenses_branch_status'), 'expenses', ['branch_code', 'status'], unique=False)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'expense_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'miscellaneous'::character varying"))
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'operational'::character varying"))
    op.create_index(op.f('ix_employee_salary_profile_employee'), 'employee_salary_profile', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_promotions_employee'), 'employee_promotions', ['employee_id'], unique=False)
    op.add_column('employee_payroll', sa.Column('add_sales_commission', sa.NUMERIC(precision=60, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employee_payroll_payroll_batch_no'), table_name='employee_payroll')
    op.create_index(op.f('ix_employee_payroll_employee'), 'employee_payroll', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_payroll_batch_no'), 'employee_payroll', ['payroll_batch_no'], unique=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.create_index(op.f('ix_customer_support_customer'), 'customer_support', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_support_branch'), 'customer_support', ['branch_code'], unique=False)
    op.create_index(op.f('ix_customer_support_assigned'), 'customer_support', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_customer_credit_notes_customer'), 'customer_credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_call_log_ticket'), 'customer_call_log', ['customer_support_id'], unique=False)
    op.create_index(op.f('ix_cac_status'), 'customer_agent_commissions', ['status'], unique=False)
    op.create_index(op.f('ix_cac_invoice_id'), 'customer_agent_commissions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_cac_agent_id'), 'customer_agent_commissions', ['customer_agent_id'], unique=False)
    op.create_index(op.f('ix_cacp_status'), 'customer_agent_commission_payments', ['status'], unique=False)
    op.create_index(op.f('ix_cacp_agent_id'), 'customer_agent_commission_payments', ['customer_agent_id'], unique=False)
    op.create_index(op.f('ix_cacpi_payment_id'), 'customer_agent_commission_payment_items', ['payment_id'], unique=False)
    op.create_index(op.f('ix_cacpi_commission_id'), 'customer_agent_commission_payment_items', ['commission_id'], unique=False)
    op.create_index(op.f('ix_cs_job_item_ticket'), 'cs_job_item', ['customer_support_id'], unique=False)
    op.create_index(op.f('ix_coupon_usage_customer'), 'coupon_usage', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coupon_usage_coupon'), 'coupon_usage', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_company_assets_grn'), 'company_assets', ['good_received_note_id'], unique=False)
    op.create_index(op.f('ix_company_assets_branch'), 'company_assets', ['branch_code'], unique=False)
    op.create_index(op.f('ix_cheque_payments_branch'), 'cheque_payments', ['branch_code'], unique=False)
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['account_code'], unique=False)
    op.create_unique_constraint(op.f('chart_of_accounts_account_code_key'), 'chart_of_accounts', ['account_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_flow_statements_statement_no'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_id'), table_name='cash_flow_statements')
    op.create_unique_constraint(op.f('cash_flow_statements_statement_no_key'), 'cash_flow_statements', ['statement_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_flow_statement_lines_id'), table_name='cash_flow_statement_lines')
    op.drop_index(op.f('ix_cash_flow_categories_id'), table_name='cash_flow_categories')
    op.drop_index(op.f('ix_cash_flow_categories_category_code'), table_name='cash_flow_categories')
    op.create_unique_constraint(op.f('cash_flow_categories_category_code_key'), 'cash_flow_categories', ['category_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bank_deposits_branch'), 'bank_deposits', ['branch_code'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_accounting_periods_id'), table_name='accounting_periods')
    op.create_index(op.f('ix_accounting_periods_year'), 'accounting_periods', ['fiscal_year'], unique=False)
    op.create_table('supplier_debit_note_settlements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('debit_note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('settlement_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('settlement_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('refund_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('applied_to_po_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('write_off_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['debit_note_id'], ['supplier_debit_notes.id'], name=op.f('supplier_debit_note_settlements_debit_note_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_debit_note_settlements_pkey'))
    )
    op.create_index(op.f('ix_sdn_settlements_debit_note_id'), 'supplier_debit_note_settlements', ['debit_note_id'], unique=False)
    op.create_index(op.f('ix_sdn_settlements_applied_to_po_id'), 'supplier_debit_note_settlements', ['applied_to_po_id'], unique=False)
    op.create_table('supplier_debit_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('debit_note_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('purchasing_return_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_code', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('purchasing_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grn_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('debit_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('tax_reversal_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('settled_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('issued_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cancelled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['purchasing_return_id'], ['purchasing_return.id'], name=op.f('supplier_debit_notes_purchasing_return_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_debit_notes_pkey')),
    sa.UniqueConstraint('debit_note_no', name=op.f('supplier_debit_notes_debit_note_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('purchasing_return_id', name=op.f('supplier_debit_notes_purchasing_return_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_supplier_debit_notes_supplier_id'), 'supplier_debit_notes', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_status'), 'supplier_debit_notes', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_purchasing_order_id'), 'supplier_debit_notes', ['purchasing_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_debit_note_no'), 'supplier_debit_notes', ['debit_note_no'], unique=True)
    op.create_index(op.f('ix_supplier_debit_notes_branch_code'), 'supplier_debit_notes', ['branch_code'], unique=False)
    op.create_index(op.f('idx_sdn_supplier_status'), 'supplier_debit_notes', ['supplier_id', 'status'], unique=False)
    # ### end Alembic commands ###
