"""Add display_id to communication_email_logs

Revision ID: 4ea2e428576c
Revises: s43_merge_all_heads
Create Date: 2026-07-11 15:20:10.236555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4ea2e428576c'
down_revision = 's43_merge_all_heads'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_email_logs', sa.Column('display_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_communication_email_logs_display_id'), 'communication_email_logs', ['display_id'], unique=False)
    op.drop_index('ix_communication_email_logs_document_id', table_name='communication_email_logs', if_exists=True)
    op.drop_index('ix_communication_email_logs_document_type', table_name='communication_email_logs', if_exists=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_communication_email_logs_document_type', 'communication_email_logs', ['document_type'], unique=False)
    op.create_index('ix_communication_email_logs_document_id', 'communication_email_logs', ['document_id'], unique=False)
    op.drop_index(op.f('ix_communication_email_logs_display_id'), table_name='communication_email_logs')
    op.drop_column('communication_email_logs', 'display_id')
    # ### end Alembic commands ###
