"""Add credit_note_amount to invoices

Revision ID: 566f95ee7679
Revises: a54facc3979d
Create Date: 2026-01-27 13:52:55.327695

"""
from alembic import op
import sqlalchemy as sa


revision = '566f95ee7679'
down_revision = 'a54facc3979d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing data
    op.add_column('invoices', sa.Column('credit_note_amount', sa.Numeric(precision=60, scale=2), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE invoices SET credit_note_amount = 0 WHERE credit_note_amount IS NULL")
    # Make column NOT NULL
    op.alter_column('invoices', 'credit_note_amount', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'credit_note_amount')
    # ### end Alembic commands ###
