"""Add credit_note_amount to invoices

Revision ID: 7fd21e43667a
Revises: a54facc3979d
Create Date: 2026-01-27 12:40:20.677957

"""
from alembic import op
import sqlalchemy as sa


revision = '7fd21e43667a'
down_revision = 'a54facc3979d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('invoices', sa.Column('credit_note_amount', sa.Numeric(precision=60, scale=2), nullable=True))
    # Update existing rows to have default value
    op.execute("UPDATE invoices SET credit_note_amount = 0 WHERE credit_note_amount IS NULL")
    # Now make it NOT NULL
    op.alter_column('invoices', 'credit_note_amount', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'credit_note_amount')
    # ### end Alembic commands ###
