"""Add communication models

Revision ID: 874888ed5142
Revises: s39_audit_passcode
Create Date: 2026-07-02 10:51:46.872589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '874888ed5142'
down_revision = 's39_audit_passcode'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('cc_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_email_logs_document_id'), 'communication_email_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_communication_email_logs_document_type'), 'communication_email_logs', ['document_type'], unique=False)
    op.create_index(op.f('ix_communication_email_logs_id'), 'communication_email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_email_logs_status'), 'communication_email_logs', ['status'], unique=False)
    op.create_table('communication_email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_email_templates_document_type'), 'communication_email_templates', ['document_type'], unique=True)
    op.create_index(op.f('ix_communication_email_templates_id'), 'communication_email_templates', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_email_templates_id'), table_name='communication_email_templates')
    op.drop_index(op.f('ix_communication_email_templates_document_type'), table_name='communication_email_templates')
    op.drop_table('communication_email_templates')
    op.drop_index(op.f('ix_communication_email_logs_status'), table_name='communication_email_logs')
    op.drop_index(op.f('ix_communication_email_logs_id'), table_name='communication_email_logs')
    op.drop_index(op.f('ix_communication_email_logs_document_type'), table_name='communication_email_logs')
    op.drop_index(op.f('ix_communication_email_logs_document_id'), table_name='communication_email_logs')
    op.drop_table('communication_email_logs')
    # ### end Alembic commands ###
