"""make_sales_quote_sale_rep_optional

Revision ID: 89784ea2a165
Revises: s11_15_workflow_fields
Create Date: 2026-04-04 15:52:27.944508

"""
from alembic import op
import sqlalchemy as sa

revision = '89784ea2a165'
down_revision = 's11_15_workflow_fields'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # Make sale_rep_id optional on sales_quotes (sales representative is no longer required)
    op.alter_column('sales_quotes', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)

def downgrade() -> None:
    # Revert: make sale_rep_id required again (existing NULLs must be resolved first)
    op.alter_column('sales_quotes', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_periods_year'), table_name='accounting_periods')
    op.create_index(op.f('ix_accounting_periods_id'), 'accounting_periods', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('cash_flow_categories_category_code_key'), 'cash_flow_categories', type_='unique')
    op.create_index(op.f('ix_cash_flow_categories_category_code'), 'cash_flow_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_cash_flow_categories_id'), 'cash_flow_categories', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statement_lines_id'), 'cash_flow_statement_lines', ['id'], unique=False)
    op.drop_constraint(op.f('cash_flow_statements_statement_no_key'), 'cash_flow_statements', type_='unique')
    op.create_index(op.f('ix_cash_flow_statements_id'), 'cash_flow_statements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_statement_no'), 'cash_flow_statements', ['statement_no'], unique=True)
    op.drop_constraint(op.f('chart_of_accounts_account_code_key'), 'chart_of_accounts', type_='unique')
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_account_code'), 'chart_of_accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_cacpi_commission_id'), table_name='customer_agent_commission_payment_items')
    op.drop_index(op.f('ix_cacpi_payment_id'), table_name='customer_agent_commission_payment_items')
    op.drop_index(op.f('ix_cacp_agent_id'), table_name='customer_agent_commission_payments')
    op.drop_index(op.f('ix_cacp_status'), table_name='customer_agent_commission_payments')
    op.drop_index(op.f('ix_cac_agent_id'), table_name='customer_agent_commissions')
    op.drop_index(op.f('ix_cac_invoice_id'), table_name='customer_agent_commissions')
    op.drop_index(op.f('ix_cac_status'), table_name='customer_agent_commissions')
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.drop_index(op.f('ix_employee_payroll_batch_no'), table_name='employee_payroll')
    op.create_index(op.f('ix_employee_payroll_payroll_batch_no'), 'employee_payroll', ['payroll_batch_no'], unique=False)
    op.drop_column('employee_payroll', 'add_sales_commission')
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'operational'::character varying"))
    op.alter_column('expenses', 'expense_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'other_expenses'::character varying"))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_unique_constraint(None, 'expenses', ['expenses_no'])
    op.create_index(op.f('ix_general_ledger_id'), 'general_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_good_received_note_branch_code'), 'good_received_note', ['branch_code'], unique=False)
    op.create_index(op.f('ix_invoice_card_payments_invoice_id'), 'invoice_card_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_card_payments_payment_card_id'), 'invoice_card_payments', ['payment_card_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.drop_constraint(op.f('invoices_invoice_no_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_approval_status'), 'invoices', ['approval_status'], unique=False)
    op.create_index(op.f('ix_invoices_branch_code'), 'invoices', ['branch_code'], unique=False)
    op.create_index(op.f('ix_invoices_created_date'), 'invoices', ['created_date'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_payment_status'), 'invoices', ['payment_status'], unique=False)
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_no'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_constraint(op.f('journal_entries_journal_entry_no_key'), 'journal_entries', type_='unique')
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_journal_entry_no'), 'journal_entries', ['journal_entry_no'], unique=True)
    op.drop_index(op.f('ix_je_lines_account'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_je_lines_entry'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_journal_entry_lines_id'), 'journal_entry_lines', ['id'], unique=False)
    op.drop_index(op.f('ix_monthly_sales_branch_period'), table_name='monthly_branch_sales_summary')
    op.create_index('idx_mbs_branch_period', 'monthly_branch_sales_summary', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_index(op.f('ix_payroll_batches_id'), 'payroll_batches', ['id'], unique=False)
    op.alter_column('petty_cash', 'petty_cash_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('petty_cash', 'opening_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'current_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'opened_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('petty_cash', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_pct_fund_id'), table_name='petty_cash_transaction')
    op.drop_index(op.f('ix_pct_txn_date'), table_name='petty_cash_transaction')
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_items_brand_id'), 'products', ['items_brand_id'], unique=False)
    op.alter_column('purchasing_orders', 'purchasing_invoice_no',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_purchasing_orders_branch_code'), 'purchasing_orders', ['branch_code'], unique=False)
    op.create_index(op.f('ix_purchasing_orders_status'), 'purchasing_orders', ['status'], unique=False)
    op.alter_column('reimbursement_items', 'receipt_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_reimbursement_items_reimbursement_id'), table_name='reimbursement_items')
    op.alter_column('reimbursements', 'reimbursement_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reimbursements', 'branch_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('reimbursements', 'claim_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('reimbursements', 'reimbursement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('reimbursements', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('reimbursements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reimbursements', 'verified_by',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('reimbursements', 'remark',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reimbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reimbursements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_reimbursements_status'), table_name='reimbursements')
    op.create_index(op.f('ix_reimbursements_employee_id'), 'reimbursements', ['employee_id'], unique=False)
    op.drop_column('reimbursements', 'reimbursement_amount')
    op.drop_column('reimbursements', 'bill_date')
    op.create_index(op.f('ix_sale_return_added_date'), 'sale_return', ['added_date'], unique=False)
    op.create_index(op.f('ix_sale_return_branch_code'), 'sale_return', ['branch_code'], unique=False)
    op.create_index(op.f('ix_sale_return_invoice_id'), 'sale_return', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sale_return_status'), 'sale_return', ['status'], unique=False)
    op.alter_column('sales_officer_monthly_commissions', 'commission_percentage',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_sales_commission_employee'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_period'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_status'), table_name='sales_officer_monthly_commissions')
    op.drop_index(op.f('ix_sales_commission_summary'), table_name='sales_officer_monthly_commissions')
    op.drop_constraint(op.f('sales_commission_employee_period_unique'), 'sales_officer_monthly_commissions', type_='unique')
    op.create_index('idx_sales_comm_branch', 'sales_officer_monthly_commissions', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_index('idx_sales_comm_employee', 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'], unique=False)
    op.create_unique_constraint('sales_commission_unique', 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'])
    op.drop_constraint(op.f('sales_officer_monthly_commissions_monthly_sales_summary_id_fkey'), 'sales_officer_monthly_commissions', type_='foreignkey')
    op.drop_constraint(op.f('sales_officer_monthly_commissions_paid_in_payroll_id_fkey'), 'sales_officer_monthly_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'sales_officer_monthly_commissions', 'monthly_branch_sales_summary', ['monthly_sales_summary_id'], ['id'])
    op.create_foreign_key(None, 'sales_officer_monthly_commissions', 'employee_payroll', ['paid_in_payroll_id'], ['id'])
    op.alter_column('sales_quotes', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_sales_stock_branch_code'), 'sales_stock', ['branch_code'], unique=False)
    op.create_index(op.f('ix_sales_stock_product_id'), 'sales_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_stock_status'), 'sales_stock', ['status'], unique=False)
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_column('user_notifications', 'category')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sales_stock_status'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_product_id'), table_name='sales_stock')
    op.drop_index(op.f('ix_sales_stock_branch_code'), table_name='sales_stock')
    op.alter_column('sales_quotes', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'sales_officer_monthly_commissions', type_='foreignkey')
    op.drop_constraint(None, 'sales_officer_monthly_commissions', type_='foreignkey')
    op.create_foreign_key(op.f('sales_officer_monthly_commissions_paid_in_payroll_id_fkey'), 'sales_officer_monthly_commissions', 'payroll_batches', ['paid_in_payroll_id'], ['id'])
    op.create_foreign_key(op.f('sales_officer_monthly_commissions_monthly_sales_summary_id_fkey'), 'sales_officer_monthly_commissions', 'monthly_branch_sales_summary', ['monthly_sales_summary_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sales_commission_unique', 'sales_officer_monthly_commissions', type_='unique')
    op.drop_index('idx_sales_comm_employee', table_name='sales_officer_monthly_commissions')
    op.drop_index('idx_sales_comm_branch', table_name='sales_officer_monthly_commissions')
    op.create_unique_constraint(op.f('sales_commission_employee_period_unique'), 'sales_officer_monthly_commissions', ['employee_id', 'fiscal_year', 'fiscal_month'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sales_commission_summary'), 'sales_officer_monthly_commissions', ['monthly_sales_summary_id'], unique=False)
    op.create_index(op.f('ix_sales_commission_status'), 'sales_officer_monthly_commissions', ['status'], unique=False)
    op.create_index(op.f('ix_sales_commission_period'), 'sales_officer_monthly_commissions', ['fiscal_year', 'fiscal_month'], unique=False)
    op.create_index(op.f('ix_sales_commission_employee'), 'sales_officer_monthly_commissions', ['employee_id'], unique=False)
    op.alter_column('sales_officer_monthly_commissions', 'commission_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_sale_return_status'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_invoice_id'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_branch_code'), table_name='sale_return')
    op.drop_index(op.f('ix_sale_return_added_date'), table_name='sale_return')
    op.add_column('reimbursements', sa.Column('bill_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('reimbursements', sa.Column('reimbursement_amount', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reimbursements_employee_id'), table_name='reimbursements')
    op.create_index(op.f('ix_reimbursements_status'), 'reimbursements', ['status'], unique=False)
    op.alter_column('reimbursements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'remark',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reimbursements', 'verified_by',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reimbursements', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reimbursements', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('reimbursements', 'reimbursement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('reimbursements', 'claim_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reimbursements', 'branch_code',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('reimbursements', 'reimbursement_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_reimbursement_items_reimbursement_id'), 'reimbursement_items', ['reimbursement_id'], unique=False)
    op.alter_column('reimbursement_items', 'receipt_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_purchasing_orders_status'), table_name='purchasing_orders')
    op.drop_index(op.f('ix_purchasing_orders_branch_code'), table_name='purchasing_orders')
    op.alter_column('purchasing_orders', 'purchasing_invoice_no',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_products_items_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.create_index(op.f('ix_pct_txn_date'), 'petty_cash_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_pct_fund_id'), 'petty_cash_transaction', ['petty_cash_id'], unique=False)
    op.alter_column('petty_cash', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('petty_cash', 'opened_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('petty_cash', 'current_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'opening_balance',
               existing_type=sa.NUMERIC(precision=60, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('petty_cash', 'petty_cash_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_payroll_batches_id'), table_name='payroll_batches')
    op.drop_index('idx_mbs_branch_period', table_name='monthly_branch_sales_summary')
    op.create_index(op.f('ix_monthly_sales_branch_period'), 'monthly_branch_sales_summary', ['branch_code', 'fiscal_year', 'fiscal_month'], unique=False)
    op.drop_index(op.f('ix_journal_entry_lines_id'), table_name='journal_entry_lines')
    op.create_index(op.f('ix_je_lines_entry'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_je_lines_account'), 'journal_entry_lines', ['account_id'], unique=False)
    op.drop_index(op.f('ix_journal_entries_journal_entry_no'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.create_unique_constraint(op.f('journal_entries_journal_entry_no_key'), 'journal_entries', ['journal_entry_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_index(op.f('ix_journal_entries_no'), 'journal_entries', ['journal_entry_no'], unique=False)
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['entry_date'], unique=False)
    op.drop_index(op.f('ix_invoices_payment_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_approval_status'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_no_key'), 'invoices', ['invoice_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_card_payments_payment_card_id'), table_name='invoice_card_payments')
    op.drop_index(op.f('ix_invoice_card_payments_invoice_id'), table_name='invoice_card_payments')
    op.drop_index(op.f('ix_good_received_note_branch_code'), table_name='good_received_note')
    op.drop_index(op.f('ix_general_ledger_id'), table_name='general_ledger')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.alter_column('expenses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'expense_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'other_expenses'::character varying"))
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'operational'::character varying"))
    op.add_column('employee_payroll', sa.Column('add_sales_commission', sa.NUMERIC(precision=60, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employee_payroll_payroll_batch_no'), table_name='employee_payroll')
    op.create_index(op.f('ix_employee_payroll_batch_no'), 'employee_payroll', ['payroll_batch_no'], unique=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.create_index(op.f('ix_cac_status'), 'customer_agent_commissions', ['status'], unique=False)
    op.create_index(op.f('ix_cac_invoice_id'), 'customer_agent_commissions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_cac_agent_id'), 'customer_agent_commissions', ['customer_agent_id'], unique=False)
    op.create_index(op.f('ix_cacp_status'), 'customer_agent_commission_payments', ['status'], unique=False)
    op.create_index(op.f('ix_cacp_agent_id'), 'customer_agent_commission_payments', ['customer_agent_id'], unique=False)
    op.create_index(op.f('ix_cacpi_payment_id'), 'customer_agent_commission_payment_items', ['payment_id'], unique=False)
    op.create_index(op.f('ix_cacpi_commission_id'), 'customer_agent_commission_payment_items', ['commission_id'], unique=False)
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_code'), 'chart_of_accounts', ['account_code'], unique=False)
    op.create_unique_constraint(op.f('chart_of_accounts_account_code_key'), 'chart_of_accounts', ['account_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_flow_statements_statement_no'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_id'), table_name='cash_flow_statements')
    op.create_unique_constraint(op.f('cash_flow_statements_statement_no_key'), 'cash_flow_statements', ['statement_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_flow_statement_lines_id'), table_name='cash_flow_statement_lines')
    op.drop_index(op.f('ix_cash_flow_categories_id'), table_name='cash_flow_categories')
    op.drop_index(op.f('ix_cash_flow_categories_category_code'), table_name='cash_flow_categories')
    op.create_unique_constraint(op.f('cash_flow_categories_category_code_key'), 'cash_flow_categories', ['category_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_accounting_periods_id'), table_name='accounting_periods')
    op.create_index(op.f('ix_accounting_periods_year'), 'accounting_periods', ['fiscal_year'], unique=False)
    # ### end Alembic commands ###
