"""add_discount_type

Revision ID: a397723e0bec
Revises: g1a2b3c4d5e6
Create Date: 2026-01-18 05:22:50.011648

"""
from alembic import op
import sqlalchemy as sa


revision = 'a397723e0bec'
down_revision = 'g1a2b3c4d5e6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check if supplier_advance_payment table exists before creating
    if 'supplier_advance_payment' not in inspector.get_table_names():
        op.create_table('supplier_advance_payment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('advance_no', sa.String(length=50), nullable=False),
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.Column('payment_voucher_id', sa.Integer(), nullable=True),
        sa.Column('payment_date', sa.Date(), nullable=False),
        sa.Column('branch_code', sa.String(length=200), nullable=False),
        sa.Column('payment_method', sa.String(length=30), nullable=False),
        sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column('reference_number', sa.String(length=100), nullable=True),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('is_fully_applied', sa.Boolean(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_supplier_advance_payment_advance_no'), 'supplier_advance_payment', ['advance_no'], unique=True)
        op.create_index(op.f('ix_supplier_advance_payment_id'), 'supplier_advance_payment', ['id'], unique=False)
        op.create_index(op.f('ix_supplier_advance_payment_payment_date'), 'supplier_advance_payment', ['payment_date'], unique=False)
        op.create_index(op.f('ix_supplier_advance_payment_supplier_id'), 'supplier_advance_payment', ['supplier_id'], unique=False)
    
    # Check if supplier_advance_application table exists before creating
    if 'supplier_advance_application' not in inspector.get_table_names():
        op.create_table('supplier_advance_application',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('advance_id', sa.Integer(), nullable=False),
        sa.Column('grn_id', sa.Integer(), nullable=False),
        sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column('application_date', sa.Date(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['advance_id'], ['supplier_advance_payment.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['grn_id'], ['good_received_note.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_supplier_advance_application_advance_id'), 'supplier_advance_application', ['advance_id'], unique=False)
        op.create_index(op.f('ix_supplier_advance_application_grn_id'), 'supplier_advance_application', ['grn_id'], unique=False)
        op.create_index(op.f('ix_supplier_advance_application_id'), 'supplier_advance_application', ['id'], unique=False)
    
    # Check and add columns to sales_quote_items if they don't exist
    if 'sales_quote_items' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('sales_quote_items')]
        if 'discount_percentage' not in columns:
            op.add_column('sales_quote_items', sa.Column('discount_percentage', sa.Numeric(precision=60, scale=2), nullable=False, server_default=sa.text('0')))
    
    # Check and add columns to sales_quotes if they don't exist
    if 'sales_quotes' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('sales_quotes')]
        if 'discount_type' not in columns:
            op.add_column('sales_quotes', sa.Column('discount_type', sa.String(length=30), nullable=False, server_default=sa.text("'none'")))
        if 'discount_percentage' not in columns:
            op.add_column('sales_quotes', sa.Column('discount_percentage', sa.Numeric(precision=60, scale=2), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_quotes', 'discount_percentage')
    op.drop_column('sales_quotes', 'discount_type')
    op.drop_column('sales_quote_items', 'discount_percentage')
    op.drop_index(op.f('ix_supplier_advance_application_id'), table_name='supplier_advance_application')
    op.drop_index(op.f('ix_supplier_advance_application_grn_id'), table_name='supplier_advance_application')
    op.drop_index(op.f('ix_supplier_advance_application_advance_id'), table_name='supplier_advance_application')
    op.drop_table('supplier_advance_application')
    op.drop_index(op.f('ix_supplier_advance_payment_supplier_id'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_payment_date'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_id'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_advance_no'), table_name='supplier_advance_payment')
    op.drop_table('supplier_advance_payment')
    # ### end Alembic commands ###
