"""add bank transfer verification fields

Revision ID: a54facc3979d
Revises: merge_heads_jan25
Create Date: 2026-01-27 09:27:21.500228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a54facc3979d'
down_revision = 'merge_heads_jan25'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_deposits', 'verified_by')
    op.drop_column('bank_deposits', 'rejection_reason')
    op.drop_column('bank_deposits', 'verified_date')
    op.drop_index(op.f('ix_coupon_usage_coupon_customer'), table_name='coupon_usage')
    op.create_unique_constraint(None, 'customer_gift_voucher', ['barcode_no'])
    op.alter_column('invoice_items', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('invoices', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'bank_transfer_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(op.f('invoices_sale_rep_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'accounts_user', ['sale_rep_id'], ['id'])
    op.drop_constraint(op.f('fk_purchasing_orders_branch_code'), 'purchasing_orders', type_='foreignkey')
    op.alter_column('sale_return', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sale_return', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'sale_return', 'accounts_user', ['processed_by'], ['id'])
    op.create_foreign_key(None, 'sale_return', 'accounts_user', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'sale_return', 'accounts_user', ['created_by'], ['id'])
    op.alter_column('sale_return_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sale_return_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_return_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sale_return_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'sale_return', type_='foreignkey')
    op.drop_constraint(None, 'sale_return', type_='foreignkey')
    op.drop_constraint(None, 'sale_return', type_='foreignkey')
    op.alter_column('sale_return', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sale_return', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('fk_purchasing_orders_branch_code'), 'purchasing_orders', 'branches', ['branch_code'], ['branch_code'], ondelete='RESTRICT')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_sale_rep_id_fkey'), 'invoices', 'employees', ['sale_rep_id'], ['id'])
    op.alter_column('invoices', 'bank_transfer_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('invoices', 'sale_rep_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoice_items', 'barcode',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'customer_gift_voucher', type_='unique')
    op.create_index(op.f('ix_coupon_usage_coupon_customer'), 'coupon_usage', ['coupon_id', 'customer_id'], unique=False)
    op.add_column('bank_deposits', sa.Column('verified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bank_deposits', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bank_deposits', sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
