"""add sales quotes and quote items tables

Revision ID: a6ef1329e39d
Revises: bcaec621ce04
Create Date: 2026-01-11 03:55:46.170068

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "a6ef1329e39d"
down_revision = "bcaec621ce04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, rename the users table to accounts_user
    op.rename_table("users", "accounts_user")

    # Drop and recreate the index with new table name
    op.drop_index(op.f("ix_users_id"), table_name="accounts_user")
    op.create_index(op.f("ix_accounts_user_id"), "accounts_user", ["id"], unique=False)

    # Now create the new tables that reference accounts_user
    op.create_table(
        "sales_quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_no", sa.String(length=200), nullable=False),
        sa.Column("quote_type", sa.String(length=30), nullable=False),
        sa.Column("branch_code", sa.String(length=200), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("sale_rep_id", sa.Integer(), nullable=False),
        sa.Column("customer_agent_id", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("created_date_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("expected_delivery_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("approval", sa.Boolean(), nullable=False),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column("special", sa.Boolean(), nullable=False),
        sa.Column("sys_code", sa.Integer(), nullable=True),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("parent_quote_id", sa.Integer(), nullable=True),
        sa.Column("payment_terms", sa.Text(), nullable=True),
        sa.Column("delivery_terms", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("terms_conditions", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("discount_type", sa.String(length=30), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("converted_to_invoice_id", sa.Integer(), nullable=True),
        sa.Column("converted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("converted_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["converted_by"],
            ["accounts_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["converted_to_invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_agent_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_quote_id"],
            ["sales_quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_rep_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_quotes_id"), "sales_quotes", ["id"], unique=False)
    op.create_index(
        op.f("ix_sales_quotes_quote_no"), "sales_quotes", ["quote_no"], unique=True
    )
    op.create_table(
        "login_shortcodes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login_short_code", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("login_short_code"),
    )
    op.create_index(
        op.f("ix_login_shortcodes_user_id"),
        "login_shortcodes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "petty_cash",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_no", sa.String(length=50), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("branch_code", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("receipt_reference", sa.String(length=200), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_no"),
    )
    op.create_index(op.f("ix_petty_cash_id"), "petty_cash", ["id"], unique=False)
    op.create_table(
        "sales_quote_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("selling_price", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column(
            "minimum_selling_price", sa.Numeric(precision=60, scale=2), nullable=False
        ),
        sa.Column("warrenty_month", sa.String(length=30), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("min_price", sa.Numeric(precision=60, scale=2), nullable=True),
        sa.Column("max_price", sa.Numeric(precision=60, scale=2), nullable=True),
        sa.Column("is_price_estimate", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=60, scale=2), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["sales_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_quote_items_id"), "sales_quote_items", ["id"], unique=False
    )
    op.drop_index(op.f("ix_advance_receipt_id"), table_name="advance_receipt")
    op.drop_table("advance_receipt")
    op.drop_constraint(
        op.f("accounts_user_branches_user_id_fkey"),
        "accounts_user_branches",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "accounts_user_branches", "accounts_user", ["user_id"], ["id"]
    )
    op.drop_constraint(
        op.f("accounts_user_groups_user_id_fkey"),
        "accounts_user_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "accounts_user_groups", "accounts_user", ["user_id"], ["id"]
    )
    op.drop_constraint(
        op.f("accounts_user_user_permissions_user_id_fkey"),
        "accounts_user_user_permissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "accounts_user_user_permissions", "accounts_user", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_company_assets_barcode"), table_name="company_assets")
    op.drop_index(op.f("ix_company_assets_inventory_no"), table_name="company_assets")
    op.create_unique_constraint(None, "company_assets", ["barcode"])
    op.create_unique_constraint(None, "company_assets", ["inventory_no"])
    op.add_column(
        "credit_payments", sa.Column("customer_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "credit_payments",
        sa.Column("amount", sa.Numeric(precision=60, scale=2), nullable=True),
    )
    op.add_column(
        "credit_payments",
        sa.Column("credit_terms", sa.String(length=100), nullable=True),
    )
    op.add_column("credit_payments", sa.Column("due_date", sa.Date(), nullable=True))
    op.add_column(
        "credit_payments", sa.Column("status", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "credit_payments", sa.Column("created_date", sa.TIMESTAMP(), nullable=True)
    )
    op.create_foreign_key(None, "credit_payments", "customers", ["customer_id"], ["id"])
    op.drop_constraint(
        op.f("customer_support_assigned_user_id_fkey"),
        "customer_support",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "customer_support", "accounts_user", ["assigned_user_id"], ["id"]
    )
    op.drop_constraint(op.f("employees_user_id_fkey"), "employees", type_="foreignkey")
    op.create_foreign_key(None, "employees", "accounts_user", ["user_id"], ["id"])
    op.add_column("invoices", sa.Column("source_quote_id", sa.Integer(), nullable=True))
    op.add_column(
        "invoices", sa.Column("source_quote_type", sa.String(length=30), nullable=True)
    )
    op.create_foreign_key(None, "invoices", "sales_quotes", ["source_quote_id"], ["id"])
    op.drop_constraint(
        op.f("item_transfer_note_approved_approved_user_id_fkey"),
        "item_transfer_note_approved",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "item_transfer_note_approved",
        "accounts_user",
        ["approved_user_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_sales_stock_barcode"), table_name="sales_stock")
    op.drop_index(op.f("ix_sales_stock_product_id"), table_name="sales_stock")
    op.drop_index(op.f("ix_sales_stock_status"), table_name="sales_stock")
    op.alter_column(
        "supplier_credits_settle",
        "suppliers_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_foreign_key(
        None, "supplier_credits_settle", "supplier", ["suppliers_id"], ["id"]
    )
    op.alter_column(
        "supplier_credits_settle_transaction",
        "supplier_credit_settle_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_foreign_key(
        None,
        "supplier_credits_settle_transaction",
        "supplier_credits_settle",
        ["supplier_credit_settle_id"],
        ["id"],
    )
    op.add_column(
        "vouchers", sa.Column("voucher_number", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "vouchers", sa.Column("voucher_type", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "vouchers",
        sa.Column("amount", sa.Numeric(precision=60, scale=2), nullable=True),
    )
    op.add_column("vouchers", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "vouchers", sa.Column("branch_code", sa.String(length=200), nullable=True)
    )
    op.add_column("vouchers", sa.Column("created_date", sa.TIMESTAMP(), nullable=True))
    op.add_column("vouchers", sa.Column("status", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vouchers", "status")
    op.drop_column("vouchers", "created_date")
    op.drop_column("vouchers", "branch_code")
    op.drop_column("vouchers", "description")
    op.drop_column("vouchers", "amount")
    op.drop_column("vouchers", "voucher_type")
    op.drop_column("vouchers", "voucher_number")
    op.drop_constraint(None, "supplier_credits_settle_transaction", type_="foreignkey")
    op.alter_column(
        "supplier_credits_settle_transaction",
        "supplier_credit_settle_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(None, "supplier_credits_settle", type_="foreignkey")
    op.alter_column(
        "supplier_credits_settle",
        "suppliers_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_sales_stock_status"), "sales_stock", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sales_stock_product_id"), "sales_stock", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_stock_barcode"), "sales_stock", ["barcode"], unique=True
    )
    op.drop_constraint(None, "item_transfer_note_approved", type_="foreignkey")
    op.create_foreign_key(
        op.f("item_transfer_note_approved_approved_user_id_fkey"),
        "item_transfer_note_approved",
        "users",
        ["approved_user_id"],
        ["id"],
    )
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_column("invoices", "source_quote_type")
    op.drop_column("invoices", "source_quote_id")
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.create_foreign_key(
        op.f("employees_user_id_fkey"), "employees", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "customer_support", type_="foreignkey")
    op.create_foreign_key(
        op.f("customer_support_assigned_user_id_fkey"),
        "customer_support",
        "users",
        ["assigned_user_id"],
        ["id"],
    )
    op.drop_constraint(None, "credit_payments", type_="foreignkey")
    op.drop_column("credit_payments", "created_date")
    op.drop_column("credit_payments", "status")
    op.drop_column("credit_payments", "due_date")
    op.drop_column("credit_payments", "credit_terms")
    op.drop_column("credit_payments", "amount")
    op.drop_column("credit_payments", "customer_id")
    op.drop_constraint(None, "company_assets", type_="unique")
    op.drop_constraint(None, "company_assets", type_="unique")
    op.create_index(
        op.f("ix_company_assets_inventory_no"),
        "company_assets",
        ["inventory_no"],
        unique=True,
    )
    op.create_index(
        op.f("ix_company_assets_barcode"), "company_assets", ["barcode"], unique=True
    )
    op.drop_constraint(None, "accounts_user_user_permissions", type_="foreignkey")
    op.create_foreign_key(
        op.f("accounts_user_user_permissions_user_id_fkey"),
        "accounts_user_user_permissions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "accounts_user_groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("accounts_user_groups_user_id_fkey"),
        "accounts_user_groups",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "accounts_user_branches", type_="foreignkey")
    op.create_foreign_key(
        op.f("accounts_user_branches_user_id_fkey"),
        "accounts_user_branches",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_table(
        "advance_receipt",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "paid_price_currency",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "paid_price",
            sa.NUMERIC(precision=14, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("special_note", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("advance_receipt_pkey")),
    )
    op.create_index(
        op.f("ix_advance_receipt_id"), "advance_receipt", ["id"], unique=False
    )

    # Rename accounts_user back to users
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts_user")
    op.create_index(op.f("ix_users_id"), "accounts_user", ["id"], unique=False)
    op.rename_table("accounts_user", "users")

    op.drop_index(op.f("ix_sales_quote_items_id"), table_name="sales_quote_items")
    op.drop_table("sales_quote_items")
    op.drop_index(op.f("ix_petty_cash_id"), table_name="petty_cash")
    op.drop_table("petty_cash")
    op.drop_index(op.f("ix_login_shortcodes_user_id"), table_name="login_shortcodes")
    op.drop_table("login_shortcodes")
    op.drop_index(op.f("ix_sales_quotes_quote_no"), table_name="sales_quotes")
    op.drop_index(op.f("ix_sales_quotes_id"), table_name="sales_quotes")
    op.drop_table("sales_quotes")
    # ### end Alembic commands ###
