"""remove min_price and max_price from sales_quote_items

Revision ID: bd0a3abec589
Revises: add_supplier_payments
Create Date: 2026-01-16 19:09:21.210466

"""
from alembic import op
import sqlalchemy as sa


revision = 'bd0a3abec589'
down_revision = 'add_supplier_payments'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_locations_branch_code'), 'good_received_locations', type_='foreignkey')
    op.create_foreign_key(None, 'good_received_locations', 'branches', ['branch_code'], ['branch_code'])
    op.drop_constraint(op.f('minimum_price_product_id_fkey'), 'minimum_price', type_='foreignkey')
    op.create_foreign_key(None, 'minimum_price', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sales_quote_items', 'max_price')
    op.drop_column('sales_quote_items', 'min_price')
    op.drop_index(op.f('ix_supplier_payments_branch_code'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_payment_date'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_status'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.create_index(op.f('ix_supplier_payments_id'), 'supplier_payments', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payments_id'), table_name='supplier_payments')
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_status'), 'supplier_payments', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_payments_payment_date'), 'supplier_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_payments_branch_code'), 'supplier_payments', ['branch_code'], unique=False)
    op.add_column('sales_quote_items', sa.Column('min_price', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_quote_items', sa.Column('max_price', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'minimum_price', type_='foreignkey')
    op.create_foreign_key(op.f('minimum_price_product_id_fkey'), 'minimum_price', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'good_received_locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_locations_branch_code'), 'good_received_locations', 'branches', ['branch_code'], ['branch_code'], ondelete='CASCADE')
    # ### end Alembic commands ###
