"""add_payment_cards_and_invoice_card_payments_tables

Revision ID: def053c91ef9
Revises: e1583b82211b
Create Date: 2026-01-29 13:55:56.846180

"""
from alembic import op
import sqlalchemy as sa


revision = 'def053c91ef9'
down_revision = 'e1583b82211b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('service_charge_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_name')
    )
    op.create_index(op.f('ix_payment_cards_id'), 'payment_cards', ['id'], unique=False)
    op.create_table('invoice_card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_card_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('service_charge', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_card_id'], ['payment_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_card_payments_id'), 'invoice_card_payments', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_card_payments_id'), table_name='invoice_card_payments')
    op.drop_table('invoice_card_payments')
    op.drop_index(op.f('ix_payment_cards_id'), table_name='payment_cards')
    op.drop_table('payment_cards')
    # ### end Alembic commands ###
