"""Add missing tables to alembic

Revision ID: e1583b82211b
Revises: 30cbd197afc6
Create Date: 2026-01-29 01:01:12.113060

"""
from alembic import op
import sqlalchemy as sa


revision = 'e1583b82211b'
down_revision = '30cbd197afc6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_price_currency', sa.String(length=3), nullable=False),
    sa.Column('paid_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('special_note', sa.String(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_receipt_id'), 'advance_receipt', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=False),
    sa.Column('company_telephone_number', sa.String(length=12), nullable=True),
    sa.Column('company_fax_number', sa.String(length=12), nullable=True),
    sa.Column('company_email', sa.String(length=254), nullable=False),
    sa.Column('company_logo_id', sa.Integer(), nullable=True),
    sa.Column('depreciation_rate', sa.Float(), nullable=False),
    sa.Column('number_of_annual_leaves', sa.Integer(), nullable=False),
    sa.Column('number_of_casual_leaves', sa.Integer(), nullable=False),
    sa.Column('number_of_medical_leaves', sa.Integer(), nullable=False),
    sa.Column('amex_card_surcharge', sa.Float(), nullable=False),
    sa.Column('visa_card_surcharge', sa.Float(), nullable=False),
    sa.Column('master_card_surcharge', sa.Float(), nullable=False),
    sa.Column('fiscal_year_start', sa.String(length=10), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('tax_registration_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_frequency', sa.String(length=50), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('supplier_advance_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('payment_voucher_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('is_fully_applied', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_advance_payment_advance_no'), 'supplier_advance_payment', ['advance_no'], unique=True)
    op.create_index(op.f('ix_supplier_advance_payment_id'), 'supplier_advance_payment', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_advance_payment_payment_date'), 'supplier_advance_payment', ['payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_advance_payment_supplier_id'), 'supplier_advance_payment', ['supplier_id'], unique=False)
    op.create_table('supplier_credits_settle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_credits_settle_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('suppliers_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['suppliers_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_credits_settle_id'), 'supplier_credits_settle', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('desktop_notifications', sa.Boolean(), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=True),
    sa.Column('items_per_page', sa.Integer(), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('currency_format', sa.String(length=10), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('web_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_posts_id'), 'web_posts', ['id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weekday', sa.String(length=12), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('work_mins', sa.Integer(), nullable=False),
    sa.Column('ot_mins', sa.Integer(), nullable=False),
    sa.Column('full_attended_mins', sa.Integer(), nullable=False),
    sa.Column('late_mins', sa.Integer(), nullable=False),
    sa.Column('early_mins', sa.Integer(), nullable=False),
    sa.Column('absent_mins', sa.Integer(), nullable=False),
    sa.Column('leave_mins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['customer_cupon_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id')
    )
    op.create_table('coupon_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('used_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['customer_cupon_codes.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usage_id'), 'coupon_usage', ['id'], unique=False)
    op.create_table('cs_job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('job_status', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_support_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warrent_claim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_support_id'], ['customer_support.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warrent_claim_id'], ['warranty_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_job_item_id'), 'cs_job_item', ['id'], unique=False)
    op.create_table('customer_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('contact_person', sa.String(length=60), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('customer_support_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_support_id'], ['customer_support.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_call_log_id'), 'customer_call_log', ['id'], unique=False)
    op.create_table('employee_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('add_1_name', sa.String(length=100), nullable=True),
    sa.Column('add_1_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_2_name', sa.String(length=100), nullable=True),
    sa.Column('add_2_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_sales_commision', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_salary_advance', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_reimbursements', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_epf_employee', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_etf_employee', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_stamp_duty', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_late_deductions', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('epf_employer', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('etf_employer', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('less_salary_advance_repayment', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_payroll_id'), 'employee_payroll', ['id'], unique=False)
    op.create_table('employee_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('appointed_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_promotions_id'), 'employee_promotions', ['id'], unique=False)
    op.create_table('employee_salary_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('add_1_name', sa.String(length=100), nullable=True),
    sa.Column('add_1_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.Column('add_2_name', sa.String(length=100), nullable=True),
    sa.Column('add_2_value', sa.Numeric(precision=60, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_salary_profile_id'), 'employee_salary_profile', ['id'], unique=False)
    op.create_table('good_received_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_received_no', sa.String(length=200), nullable=False),
    sa.Column('good_received_date', sa.Date(), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=200), nullable=False),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('good_received_locations_id', sa.Integer(), nullable=False),
    sa.Column('purchasingorders_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_locations_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['purchasingorders_id'], ['purchasing_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('good_received_no')
    )
    op.create_index(op.f('ix_good_received_note_id'), 'good_received_note', ['id'], unique=False)
    op.create_table('item_receive_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_transfer_note_id', sa.Integer(), nullable=False),
    sa.Column('received_approval_status', sa.SmallInteger(), nullable=False),
    sa.Column('received_note', sa.String(length=355), nullable=True),
    sa.Column('recieved_user', sa.Integer(), nullable=True),
    sa.Column('recieved_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_transfer_note_id'], ['item_transfer_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_receive_note_id'), 'item_receive_note', ['id'], unique=False)
    op.create_table('item_transfer_note_approved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_transfer_note_id', sa.Integer(), nullable=True),
    sa.Column('approved_status', sa.SmallInteger(), nullable=False),
    sa.Column('approval_note', sa.String(length=355), nullable=True),
    sa.Column('approved_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_user_id'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['item_transfer_note_id'], ['item_transfer_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_approved_id'), 'item_transfer_note_approved', ['id'], unique=False)
    op.create_table('item_transfer_note_item_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('itemtransfernote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemtransfernote_id'], ['item_transfer_note.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_item_product_id'), 'item_transfer_note_item_product', ['id'], unique=False)
    op.create_table('item_transfer_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('itemtransfernote_id', sa.Integer(), nullable=False),
    sa.Column('item_recieved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['itemtransfernote_id'], ['item_transfer_note.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfer_note_items_id'), 'item_transfer_note_items', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('leave_type', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('leave_reason', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('leave_duration', sa.Float(), nullable=False),
    sa.Column('leave_time', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_table('reimbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('reimbursement_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('bill_image_path', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_reimbursements_id'), 'reimbursements', ['id'], unique=False)
    op.create_table('report_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_executions_id'), 'report_executions', ['id'], unique=False)
    op.create_table('salary_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_deductions_id'), 'salary_deductions', ['id'], unique=False)
    op.create_table('sale_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('good_received_locations_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('return_reason', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('tax_refund', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('total_refund', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('refund_status', sa.String(length=30), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('refund_date', sa.Date(), nullable=True),
    sa.Column('refund_reference', sa.String(length=200), nullable=True),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts_user.id'], ),
    sa.ForeignKeyConstraint(['credit_note_id'], ['customer_credit_notes.id'], ),
    sa.ForeignKeyConstraint(['good_received_locations_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_return_no')
    )
    op.create_index(op.f('ix_sale_return_id'), 'sale_return', ['id'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_no', sa.String(length=200), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchasing_order_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=300), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('payment_for', sa.String(length=100), nullable=False),
    sa.Column('invoice_reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchasing_order_id'], ['purchasing_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_no')
    )
    op.create_index(op.f('ix_supplier_payments_id'), 'supplier_payments', ['id'], unique=False)
    op.create_table('company_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inventory_no', sa.Text(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('asigned_to', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('warranty_month', sa.String(length=30), nullable=True),
    sa.Column('good_received_note_id', sa.Integer(), nullable=True),
    sa.Column('purchasing_order_items_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['good_received_note_id'], ['good_received_note.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchasing_order_items_id'], ['purchasing_order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('inventory_no')
    )
    op.create_index(op.f('ix_company_assets_id'), 'company_assets', ['id'], unique=False)
    op.create_table('purchasing_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchasing_return_no', sa.String(length=200), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('goodreceivednote_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['goodreceivednote_id'], ['good_received_note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchasing_return_no')
    )
    op.create_index(op.f('ix_purchasing_return_id'), 'purchasing_return', ['id'], unique=False)
    op.create_table('supplier_advance_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['advance_id'], ['supplier_advance_payment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grn_id'], ['good_received_note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_advance_application_advance_id'), 'supplier_advance_application', ['advance_id'], unique=False)
    op.create_index(op.f('ix_supplier_advance_application_grn_id'), 'supplier_advance_application', ['grn_id'], unique=False)
    op.create_index(op.f('ix_supplier_advance_application_id'), 'supplier_advance_application', ['id'], unique=False)
    op.create_table('supplier_credits_settle_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('payment_method_number', sa.String(length=300), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('good_received_id', sa.Integer(), nullable=False),
    sa.Column('supplier_credit_settle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_id'], ['good_received_note.id'], ),
    sa.ForeignKeyConstraint(['supplier_credit_settle_id'], ['supplier_credits_settle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_credits_settle_transaction_id'), 'supplier_credits_settle_transaction', ['id'], unique=False)
    op.create_table('employees_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('assign_reason', sa.Text(), nullable=True),
    sa.Column('revoke_assignment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['company_assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_assets_id'), 'employees_assets', ['id'], unique=False)
    op.create_table('sales_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('good_received_note_id', sa.Integer(), nullable=False),
    sa.Column('purchasing_order_items_id', sa.Integer(), nullable=False),
    sa.Column('warranty_month', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('returned_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('purchase_return_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_note_id'], ['good_received_note.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['good_received_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchasing_return.id'], ),
    sa.ForeignKeyConstraint(['purchasing_order_items_id'], ['purchasing_order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_sales_stock_id'), 'sales_stock', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warrenty_month', sa.String(length=30), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_selling_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('sales_stock_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_stock_id'], ['sales_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('purchasing_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchasing_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('return_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchasingreturn_id', sa.Integer(), nullable=False),
    sa.Column('sales_stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchasingreturn_id'], ['purchasing_return.id'], ),
    sa.ForeignKeyConstraint(['sales_stock_id'], ['sales_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_return_items_id'), 'purchasing_return_items', ['id'], unique=False)
    op.create_table('invoice_items_barcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('good_received_items_id', sa.Integer(), nullable=False),
    sa.Column('invoice_items_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_received_items_id'], ['good_received_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_items_id'], ['invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_barcode_id'), 'invoice_items_barcode', ['id'], unique=False)
    op.create_table('sale_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('return_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('branch_code', sa.String(length=200), nullable=False),
    sa.Column('added_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sold_price', sa.Numeric(precision=60, scale=2), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=True),
    sa.Column('sales_stock_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('restockable', sa.Boolean(), nullable=False),
    sa.Column('restocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_return.id'], ),
    sa.ForeignKeyConstraint(['sales_stock_id'], ['sales_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_return_items_id'), 'sale_return_items', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_return_items_id'), table_name='sale_return_items')
    op.drop_table('sale_return_items')
    op.drop_index(op.f('ix_invoice_items_barcode_id'), table_name='invoice_items_barcode')
    op.drop_table('invoice_items_barcode')
    op.drop_index(op.f('ix_purchasing_return_items_id'), table_name='purchasing_return_items')
    op.drop_table('purchasing_return_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_sales_stock_id'), table_name='sales_stock')
    op.drop_table('sales_stock')
    op.drop_index(op.f('ix_employees_assets_id'), table_name='employees_assets')
    op.drop_table('employees_assets')
    op.drop_index(op.f('ix_supplier_credits_settle_transaction_id'), table_name='supplier_credits_settle_transaction')
    op.drop_table('supplier_credits_settle_transaction')
    op.drop_index(op.f('ix_supplier_advance_application_id'), table_name='supplier_advance_application')
    op.drop_index(op.f('ix_supplier_advance_application_grn_id'), table_name='supplier_advance_application')
    op.drop_index(op.f('ix_supplier_advance_application_advance_id'), table_name='supplier_advance_application')
    op.drop_table('supplier_advance_application')
    op.drop_index(op.f('ix_purchasing_return_id'), table_name='purchasing_return')
    op.drop_table('purchasing_return')
    op.drop_index(op.f('ix_company_assets_id'), table_name='company_assets')
    op.drop_table('company_assets')
    op.drop_index(op.f('ix_supplier_payments_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_sale_return_id'), table_name='sale_return')
    op.drop_table('sale_return')
    op.drop_index(op.f('ix_salary_deductions_id'), table_name='salary_deductions')
    op.drop_table('salary_deductions')
    op.drop_index(op.f('ix_report_executions_id'), table_name='report_executions')
    op.drop_table('report_executions')
    op.drop_index(op.f('ix_reimbursements_id'), table_name='reimbursements')
    op.drop_table('reimbursements')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_item_transfer_note_items_id'), table_name='item_transfer_note_items')
    op.drop_table('item_transfer_note_items')
    op.drop_index(op.f('ix_item_transfer_note_item_product_id'), table_name='item_transfer_note_item_product')
    op.drop_table('item_transfer_note_item_product')
    op.drop_index(op.f('ix_item_transfer_note_approved_id'), table_name='item_transfer_note_approved')
    op.drop_table('item_transfer_note_approved')
    op.drop_index(op.f('ix_item_receive_note_id'), table_name='item_receive_note')
    op.drop_table('item_receive_note')
    op.drop_index(op.f('ix_good_received_note_id'), table_name='good_received_note')
    op.drop_table('good_received_note')
    op.drop_index(op.f('ix_employee_salary_profile_id'), table_name='employee_salary_profile')
    op.drop_table('employee_salary_profile')
    op.drop_index(op.f('ix_employee_promotions_id'), table_name='employee_promotions')
    op.drop_table('employee_promotions')
    op.drop_index(op.f('ix_employee_payroll_id'), table_name='employee_payroll')
    op.drop_table('employee_payroll')
    op.drop_index(op.f('ix_customer_call_log_id'), table_name='customer_call_log')
    op.drop_table('customer_call_log')
    op.drop_index(op.f('ix_cs_job_item_id'), table_name='cs_job_item')
    op.drop_table('cs_job_item')
    op.drop_index(op.f('ix_coupon_usage_id'), table_name='coupon_usage')
    op.drop_table('coupon_usage')
    op.drop_table('coupon_products')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_web_posts_id'), table_name='web_posts')
    op.drop_table('web_posts')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_supplier_credits_settle_id'), table_name='supplier_credits_settle')
    op.drop_table('supplier_credits_settle')
    op.drop_index(op.f('ix_supplier_advance_payment_supplier_id'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_payment_date'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_id'), table_name='supplier_advance_payment')
    op.drop_index(op.f('ix_supplier_advance_payment_advance_no'), table_name='supplier_advance_payment')
    op.drop_table('supplier_advance_payment')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_advance_receipt_id'), table_name='advance_receipt')
    op.drop_table('advance_receipt')
    # ### end Alembic commands ###
