"""remove subtotal column from sales_quotes

Revision ID: f8766ef60c46
Revises: bd0a3abec589
Create Date: 2026-01-16 19:31:57.813629

"""
from alembic import op
import sqlalchemy as sa


revision = 'f8766ef60c46'
down_revision = 'bd0a3abec589'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_quote_items', 'tax_rate')
    op.drop_column('sales_quote_items', 'discount_percent')
    op.drop_column('sales_quote_items', 'line_total')
    op.drop_constraint(op.f('sales_quotes_parent_quote_id_fkey'), 'sales_quotes', type_='foreignkey')
    op.drop_column('sales_quotes', 'payment_terms')
    op.drop_column('sales_quotes', 'discount_value')
    op.drop_column('sales_quotes', 'discount_type')
    op.drop_column('sales_quotes', 'delivery_terms')
    op.drop_column('sales_quotes', 'revision_number')
    op.drop_column('sales_quotes', 'parent_quote_id')
    op.drop_column('sales_quotes', 'subtotal')
    op.drop_column('sales_quotes', 'tax_amount')
    op.drop_column('sales_quotes', 'terms_conditions')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_quotes', sa.Column('terms_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sales_quotes', sa.Column('tax_amount', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_quotes', sa.Column('subtotal', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_quotes', sa.Column('parent_quote_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales_quotes', sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales_quotes', sa.Column('delivery_terms', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sales_quotes', sa.Column('discount_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('sales_quotes', sa.Column('discount_value', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_quotes', sa.Column('payment_terms', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_quotes_parent_quote_id_fkey'), 'sales_quotes', 'sales_quotes', ['parent_quote_id'], ['id'])
    op.add_column('sales_quote_items', sa.Column('line_total', sa.NUMERIC(precision=60, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_quote_items', sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_quote_items', sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
