#!/usr/bin/env bash
# =============================================================================
# install-openvpn-server.sh
#
# Installs and configures an OpenVPN server on the VPS so that TijaeroERP
# is accessible ONLY through the VPN tunnel.
#
# VPS public IP : 51.79.226.133
# VPN subnet    : 10.8.0.0/24   (server gets 10.8.0.1)
# App port      : 80 (nginx)  – blocked publicly, open only from tun0
# VPN port      : 1194/UDP
#
# Run on the VPS as root (or via sudo):
#   bash install-openvpn-server.sh
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
VPS_IP="51.79.226.133"
VPN_PORT="1194"
VPN_PROTO="udp"
VPN_SUBNET="10.8.0.0"
VPN_MASK="255.255.255.0"
VPN_SERVER_IP="10.8.0.1"          # tun0 gateway
EASYRSA_DIR="/etc/openvpn/easy-rsa"
PKI_DIR="$EASYRSA_DIR/pki"
SERVER_CONF="/etc/openvpn/server/server.conf"
VPN_ENV_FILE="/etc/openvpn/server/vpn.env"

# ── Sanity checks ─────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root." >&2
  exit 1
fi

echo "=== [1/9] Updating package lists ==="
apt-get update -y

echo "=== [2/9] Installing OpenVPN and Easy-RSA ==="
apt-get install -y openvpn easy-rsa ufw openssl

echo "=== [3/9] Setting up Easy-RSA PKI ==="
mkdir -p "$EASYRSA_DIR"
cp -r /usr/share/easy-rsa/. "$EASYRSA_DIR/"

cd "$EASYRSA_DIR"

# Initialise PKI (non-interactive)
./easyrsa --batch init-pki

# Build CA (no password)
./easyrsa --batch --req-cn="TijaeroERP-CA" build-ca nopass

echo "=== [4/9] Generating server certificate and key ==="
./easyrsa --batch build-server-full server nopass

echo "=== [5/9] Generating Diffie-Hellman parameters (this can take a while) ==="
./easyrsa gen-dh

echo "=== [6/9] Generating TLS-Auth / TLS-Crypt key ==="
openvpn --genkey secret "$PKI_DIR/ta.key"

echo "=== [7/9] Writing OpenVPN server configuration ==="
mkdir -p /etc/openvpn/server
mkdir -p /etc/openvpn/clients

cat > "$SERVER_CONF" <<OVPNCONF
# TijaeroERP – OpenVPN Server Config
port $VPN_PORT
proto $VPN_PROTO
dev tun

# Certificates
ca   $PKI_DIR/ca.crt
cert $PKI_DIR/issued/server.crt
key  $PKI_DIR/private/server.key
dh   $PKI_DIR/dh.pem

# TLS hardening
tls-crypt $PKI_DIR/ta.key
cipher AES-256-GCM
auth SHA256
tls-version-min 1.2

# VPN Network
server $VPN_SUBNET $VPN_MASK
ifconfig-pool-persist /var/log/openvpn/ipp.txt

# Keep alive
keepalive 10 120
max-clients 50
persist-key
persist-tun

# Logging
status  /var/log/openvpn/openvpn-status.log
log-append /var/log/openvpn/openvpn.log
verb 3
mute 20

# Push DNS + default gateway to clients (clients route all traffic via VPN)
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

user  nobody
group nogroup
OVPNCONF

mkdir -p /var/log/openvpn

echo "=== [8/9] Enabling IP forwarding ==="
sed -i 's/^#\?\s*net\.ipv4\.ip_forward\s*=.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=1

# Detect default outbound interface for NAT masquerade
DEFAULT_IFACE=$(ip route show default | awk '/default/ {print $5; exit}')
echo "Default interface: $DEFAULT_IFACE"

# Add NAT masquerade (persistent via /etc/ufw/before.rules)
UFW_BEFORE="/etc/ufw/before.rules"
if ! grep -q "TIJAERO-VPN-NAT" "$UFW_BEFORE"; then
  sed -i "1s/^/# TIJAERO-VPN-NAT\n*nat\n:POSTROUTING ACCEPT [0:0]\n-A POSTROUTING -s $VPN_SUBNET\/24 -o $DEFAULT_IFACE -j MASQUERADE\nCOMMIT\n\n/" "$UFW_BEFORE"
  echo "NAT masquerade added to $UFW_BEFORE"
fi

# Allow UFW forwarding policy
sed -i 's/^DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw

echo "=== [9/9] Configuring UFW firewall ==="
ufw --force reset

# Allow SSH so we don't lock ourselves out
ufw allow 22/tcp comment "SSH"

# Allow OpenVPN port from anywhere (clients need to connect)
ufw allow "$VPN_PORT/$VPN_PROTO" comment "OpenVPN"

# Allow port 80 ONLY from VPN tunnel interface (tun0 → 10.8.0.0/24)
ufw allow in on tun0 to any port 80 proto tcp comment "ERP via VPN"

# Explicitly deny port 80 from public internet
ufw deny 80/tcp comment "Block public HTTP"

# Enable UFW
ufw --force enable

echo "=== Starting and enabling OpenVPN service ==="
systemctl enable openvpn-server@server
systemctl start  openvpn-server@server

# Write vpn.env for docker-compose
cat > "$VPN_ENV_FILE" <<ENVFILE
# Auto-generated by install-openvpn-server.sh
GATEWAY_IP=$VPN_SERVER_IP
VPS_IP=$VPS_IP
ENVFILE

echo ""
echo "============================================================"
echo "  OpenVPN server installed successfully!"
echo ""
echo "  VPS public IP : $VPS_IP"
echo "  VPN port      : $VPN_PORT/$VPN_PROTO"
echo "  VPN gateway   : $VPN_SERVER_IP"
echo "  Port 80 (ERP) : accessible ONLY via VPN tunnel"
echo ""
echo "  Next steps:"
echo "    1. Run add-vpn-client.sh <clientname> to create a .ovpn config"
echo "    2. Transfer the .ovpn file to client machines"
echo "    3. Deploy the app: docker compose -f docker-compose.yml"
echo "         -f docker-compose.server.yml up -d --build"
echo "============================================================"
