"""Static ISO country reference data used to seed the `country` table.

Each row is (iso2, iso3, iso_numeric, name, currency_code, currency_symbol, phone).
This is the standard ISO 3166-1 country list plus ISO 4217 currency codes and
ITU-T E.164 calling codes — the same fields the `Country` model already
declares (see app/modules/common/models.py). Kept as a plain Python literal
(no external dataset dependency) so the migration has no new package to
install.
"""

COUNTRIES = [
    ("AF", "AFG", 4, "Afghanistan", "AFN", "؋", "93"),
    ("AL", "ALB", 8, "Albania", "ALL", "L", "355"),
    ("DZ", "DZA", 12, "Algeria", "DZD", "د.ج", "213"),
    ("AD", "AND", 20, "Andorra", "EUR", "€", "376"),
    ("AO", "AGO", 24, "Angola", "AOA", "Kz", "244"),
    ("AG", "ATG", 28, "Antigua and Barbuda", "XCD", "$", "1268"),
    ("AR", "ARG", 32, "Argentina", "ARS", "$", "54"),
    ("AM", "ARM", 51, "Armenia", "AMD", "֏", "374"),
    ("AU", "AUS", 36, "Australia", "AUD", "$", "61"),
    ("AT", "AUT", 40, "Austria", "EUR", "€", "43"),
    ("AZ", "AZE", 31, "Azerbaijan", "AZN", "₼", "994"),
    ("BS", "BHS", 44, "Bahamas", "BSD", "$", "1242"),
    ("BH", "BHR", 48, "Bahrain", "BHD", ".د.ب", "973"),
    ("BD", "BGD", 50, "Bangladesh", "BDT", "৳", "880"),
    ("BB", "BRB", 52, "Barbados", "BBD", "$", "1246"),
    ("BY", "BLR", 112, "Belarus", "BYN", "Br", "375"),
    ("BE", "BEL", 56, "Belgium", "EUR", "€", "32"),
    ("BZ", "BLZ", 84, "Belize", "BZD", "$", "501"),
    ("BJ", "BEN", 204, "Benin", "XOF", "CFA", "229"),
    ("BT", "BTN", 64, "Bhutan", "BTN", "Nu.", "975"),
    ("BO", "BOL", 68, "Bolivia", "BOB", "Bs.", "591"),
    ("BA", "BIH", 70, "Bosnia and Herzegovina", "BAM", "KM", "387"),
    ("BW", "BWA", 72, "Botswana", "BWP", "P", "267"),
    ("BR", "BRA", 76, "Brazil", "BRL", "R$", "55"),
    ("BN", "BRN", 96, "Brunei", "BND", "$", "673"),
    ("BG", "BGR", 100, "Bulgaria", "BGN", "лв", "359"),
    ("BF", "BFA", 854, "Burkina Faso", "XOF", "CFA", "226"),
    ("BI", "BDI", 108, "Burundi", "BIF", "FBu", "257"),
    ("KH", "KHM", 116, "Cambodia", "KHR", "៛", "855"),
    ("CM", "CMR", 120, "Cameroon", "XAF", "FCFA", "237"),
    ("CA", "CAN", 124, "Canada", "CAD", "$", "1"),
    ("CV", "CPV", 132, "Cabo Verde", "CVE", "$", "238"),
    ("CF", "CAF", 140, "Central African Republic", "XAF", "FCFA", "236"),
    ("TD", "TCD", 148, "Chad", "XAF", "FCFA", "235"),
    ("CL", "CHL", 152, "Chile", "CLP", "$", "56"),
    ("CN", "CHN", 156, "China", "CNY", "¥", "86"),
    ("CO", "COL", 170, "Colombia", "COP", "$", "57"),
    ("KM", "COM", 174, "Comoros", "KMF", "CF", "269"),
    ("CG", "COG", 178, "Congo", "XAF", "FCFA", "242"),
    ("CD", "COD", 180, "DR Congo", "CDF", "FC", "243"),
    ("CR", "CRI", 188, "Costa Rica", "CRC", "₡", "506"),
    ("CI", "CIV", 384, "Côte d'Ivoire", "XOF", "CFA", "225"),
    ("HR", "HRV", 191, "Croatia", "EUR", "€", "385"),
    ("CU", "CUB", 192, "Cuba", "CUP", "$", "53"),
    ("CY", "CYP", 196, "Cyprus", "EUR", "€", "357"),
    ("CZ", "CZE", 203, "Czechia", "CZK", "Kč", "420"),
    ("DK", "DNK", 208, "Denmark", "DKK", "kr", "45"),
    ("DJ", "DJI", 262, "Djibouti", "DJF", "Fdj", "253"),
    ("DM", "DMA", 212, "Dominica", "XCD", "$", "1767"),
    ("DO", "DOM", 214, "Dominican Republic", "DOP", "$", "1809"),
    ("EC", "ECU", 218, "Ecuador", "USD", "$", "593"),
    ("EG", "EGY", 818, "Egypt", "EGP", "£", "20"),
    ("SV", "SLV", 222, "El Salvador", "USD", "$", "503"),
    ("GQ", "GNQ", 226, "Equatorial Guinea", "XAF", "FCFA", "240"),
    ("ER", "ERI", 232, "Eritrea", "ERN", "Nfk", "291"),
    ("EE", "EST", 233, "Estonia", "EUR", "€", "372"),
    ("SZ", "SWZ", 748, "Eswatini", "SZL", "L", "268"),
    ("ET", "ETH", 231, "Ethiopia", "ETB", "Br", "251"),
    ("FJ", "FJI", 242, "Fiji", "FJD", "$", "679"),
    ("FI", "FIN", 246, "Finland", "EUR", "€", "358"),
    ("FR", "FRA", 250, "France", "EUR", "€", "33"),
    ("GA", "GAB", 266, "Gabon", "XAF", "FCFA", "241"),
    ("GM", "GMB", 270, "Gambia", "GMD", "D", "220"),
    ("GE", "GEO", 268, "Georgia", "GEL", "₾", "995"),
    ("DE", "DEU", 276, "Germany", "EUR", "€", "49"),
    ("GH", "GHA", 288, "Ghana", "GHS", "₵", "233"),
    ("GR", "GRC", 300, "Greece", "EUR", "€", "30"),
    ("GD", "GRD", 308, "Grenada", "XCD", "$", "1473"),
    ("GT", "GTM", 320, "Guatemala", "GTQ", "Q", "502"),
    ("GN", "GIN", 324, "Guinea", "GNF", "FG", "224"),
    ("GW", "GNB", 624, "Guinea-Bissau", "XOF", "CFA", "245"),
    ("GY", "GUY", 328, "Guyana", "GYD", "$", "592"),
    ("HT", "HTI", 332, "Haiti", "HTG", "G", "509"),
    ("HN", "HND", 340, "Honduras", "HNL", "L", "504"),
    ("HU", "HUN", 348, "Hungary", "HUF", "Ft", "36"),
    ("IS", "ISL", 352, "Iceland", "ISK", "kr", "354"),
    ("IN", "IND", 356, "India", "INR", "₹", "91"),
    ("ID", "IDN", 360, "Indonesia", "IDR", "Rp", "62"),
    ("IR", "IRN", 364, "Iran", "IRR", "﷼", "98"),
    ("IQ", "IRQ", 368, "Iraq", "IQD", "ع.د", "964"),
    ("IE", "IRL", 372, "Ireland", "EUR", "€", "353"),
    ("IL", "ISR", 376, "Israel", "ILS", "₪", "972"),
    ("IT", "ITA", 380, "Italy", "EUR", "€", "39"),
    ("JM", "JAM", 388, "Jamaica", "JMD", "$", "1876"),
    ("JP", "JPN", 392, "Japan", "JPY", "¥", "81"),
    ("JO", "JOR", 400, "Jordan", "JOD", "د.ا", "962"),
    ("KZ", "KAZ", 398, "Kazakhstan", "KZT", "₸", "7"),
    ("KE", "KEN", 404, "Kenya", "KES", "KSh", "254"),
    ("KI", "KIR", 296, "Kiribati", "AUD", "$", "686"),
    ("KP", "PRK", 408, "North Korea", "KPW", "₩", "850"),
    ("KR", "KOR", 410, "South Korea", "KRW", "₩", "82"),
    ("KW", "KWT", 414, "Kuwait", "KWD", "د.ك", "965"),
    ("KG", "KGZ", 417, "Kyrgyzstan", "KGS", "с", "996"),
    ("LA", "LAO", 418, "Laos", "LAK", "₭", "856"),
    ("LV", "LVA", 428, "Latvia", "EUR", "€", "371"),
    ("LB", "LBN", 422, "Lebanon", "LBP", "ل.ل", "961"),
    ("LS", "LSO", 426, "Lesotho", "LSL", "L", "266"),
    ("LR", "LBR", 430, "Liberia", "LRD", "$", "231"),
    ("LY", "LBY", 434, "Libya", "LYD", "ل.د", "218"),
    ("LI", "LIE", 438, "Liechtenstein", "CHF", "Fr", "423"),
    ("LT", "LTU", 440, "Lithuania", "EUR", "€", "370"),
    ("LU", "LUX", 442, "Luxembourg", "EUR", "€", "352"),
    ("MG", "MDG", 450, "Madagascar", "MGA", "Ar", "261"),
    ("MW", "MWI", 454, "Malawi", "MWK", "MK", "265"),
    ("MY", "MYS", 458, "Malaysia", "MYR", "RM", "60"),
    ("MV", "MDV", 462, "Maldives", "MVR", "Rf", "960"),
    ("ML", "MLI", 466, "Mali", "XOF", "CFA", "223"),
    ("MT", "MLT", 470, "Malta", "EUR", "€", "356"),
    ("MH", "MHL", 584, "Marshall Islands", "USD", "$", "692"),
    ("MR", "MRT", 478, "Mauritania", "MRU", "UM", "222"),
    ("MU", "MUS", 480, "Mauritius", "MUR", "₨", "230"),
    ("MX", "MEX", 484, "Mexico", "MXN", "$", "52"),
    ("FM", "FSM", 583, "Micronesia", "USD", "$", "691"),
    ("MD", "MDA", 498, "Moldova", "MDL", "L", "373"),
    ("MC", "MCO", 492, "Monaco", "EUR", "€", "377"),
    ("MN", "MNG", 496, "Mongolia", "MNT", "₮", "976"),
    ("ME", "MNE", 499, "Montenegro", "EUR", "€", "382"),
    ("MA", "MAR", 504, "Morocco", "MAD", "د.م.", "212"),
    ("MZ", "MOZ", 508, "Mozambique", "MZN", "MT", "258"),
    ("MM", "MMR", 104, "Myanmar", "MMK", "K", "95"),
    ("NA", "NAM", 516, "Namibia", "NAD", "$", "264"),
    ("NR", "NRU", 520, "Nauru", "AUD", "$", "674"),
    ("NP", "NPL", 524, "Nepal", "NPR", "₨", "977"),
    ("NL", "NLD", 528, "Netherlands", "EUR", "€", "31"),
    ("NZ", "NZL", 554, "New Zealand", "NZD", "$", "64"),
    ("NI", "NIC", 558, "Nicaragua", "NIO", "C$", "505"),
    ("NE", "NER", 562, "Niger", "XOF", "CFA", "227"),
    ("NG", "NGA", 566, "Nigeria", "NGN", "₦", "234"),
    ("MK", "MKD", 807, "North Macedonia", "MKD", "ден", "389"),
    ("NO", "NOR", 578, "Norway", "NOK", "kr", "47"),
    ("OM", "OMN", 512, "Oman", "OMR", "ر.ع.", "968"),
    ("PK", "PAK", 586, "Pakistan", "PKR", "₨", "92"),
    ("PW", "PLW", 585, "Palau", "USD", "$", "680"),
    ("PA", "PAN", 591, "Panama", "PAB", "B/.", "507"),
    ("PG", "PNG", 598, "Papua New Guinea", "PGK", "K", "675"),
    ("PY", "PRY", 600, "Paraguay", "PYG", "₲", "595"),
    ("PE", "PER", 604, "Peru", "PEN", "S/.", "51"),
    ("PH", "PHL", 608, "Philippines", "PHP", "₱", "63"),
    ("PL", "POL", 616, "Poland", "PLN", "zł", "48"),
    ("PT", "PRT", 620, "Portugal", "EUR", "€", "351"),
    ("QA", "QAT", 634, "Qatar", "QAR", "ر.ق", "974"),
    ("RO", "ROU", 642, "Romania", "RON", "lei", "40"),
    ("RU", "RUS", 643, "Russia", "RUB", "₽", "7"),
    ("RW", "RWA", 646, "Rwanda", "RWF", "FRw", "250"),
    ("KN", "KNA", 659, "Saint Kitts and Nevis", "XCD", "$", "1869"),
    ("LC", "LCA", 662, "Saint Lucia", "XCD", "$", "1758"),
    ("VC", "VCT", 670, "Saint Vincent and the Grenadines", "XCD", "$", "1784"),
    ("WS", "WSM", 882, "Samoa", "WST", "T", "685"),
    ("SM", "SMR", 674, "San Marino", "EUR", "€", "378"),
    ("ST", "STP", 678, "Sao Tome and Principe", "STN", "Db", "239"),
    ("SA", "SAU", 682, "Saudi Arabia", "SAR", "ر.س", "966"),
    ("SN", "SEN", 686, "Senegal", "XOF", "CFA", "221"),
    ("RS", "SRB", 688, "Serbia", "RSD", "дин.", "381"),
    ("SC", "SYC", 690, "Seychelles", "SCR", "₨", "248"),
    ("SL", "SLE", 694, "Sierra Leone", "SLE", "Le", "232"),
    ("SG", "SGP", 702, "Singapore", "SGD", "$", "65"),
    ("SK", "SVK", 703, "Slovakia", "EUR", "€", "421"),
    ("SI", "SVN", 705, "Slovenia", "EUR", "€", "386"),
    ("SB", "SLB", 90, "Solomon Islands", "SBD", "$", "677"),
    ("SO", "SOM", 706, "Somalia", "SOS", "S", "252"),
    ("ZA", "ZAF", 710, "South Africa", "ZAR", "R", "27"),
    ("SS", "SSD", 728, "South Sudan", "SSP", "£", "211"),
    ("ES", "ESP", 724, "Spain", "EUR", "€", "34"),
    ("LK", "LKA", 144, "Sri Lanka", "LKR", "Rs", "94"),
    ("SD", "SDN", 729, "Sudan", "SDG", "ج.س.", "249"),
    ("SR", "SUR", 740, "Suriname", "SRD", "$", "597"),
    ("SE", "SWE", 752, "Sweden", "SEK", "kr", "46"),
    ("CH", "CHE", 756, "Switzerland", "CHF", "Fr", "41"),
    ("SY", "SYR", 760, "Syria", "SYP", "£", "963"),
    ("TW", "TWN", 158, "Taiwan", "TWD", "$", "886"),
    ("TJ", "TJK", 762, "Tajikistan", "TJS", "ЅМ", "992"),
    ("TZ", "TZA", 834, "Tanzania", "TZS", "TSh", "255"),
    ("TH", "THA", 764, "Thailand", "THB", "฿", "66"),
    ("TL", "TLS", 626, "Timor-Leste", "USD", "$", "670"),
    ("TG", "TGO", 768, "Togo", "XOF", "CFA", "228"),
    ("TO", "TON", 776, "Tonga", "TOP", "T$", "676"),
    ("TT", "TTO", 780, "Trinidad and Tobago", "TTD", "$", "1868"),
    ("TN", "TUN", 788, "Tunisia", "TND", "د.ت", "216"),
    ("TR", "TUR", 792, "Turkey", "TRY", "₺", "90"),
    ("TM", "TKM", 795, "Turkmenistan", "TMT", "m", "993"),
    ("TV", "TUV", 798, "Tuvalu", "AUD", "$", "688"),
    ("UG", "UGA", 800, "Uganda", "UGX", "USh", "256"),
    ("UA", "UKR", 804, "Ukraine", "UAH", "₴", "380"),
    ("AE", "ARE", 784, "United Arab Emirates", "AED", "د.إ", "971"),
    ("GB", "GBR", 826, "United Kingdom", "GBP", "£", "44"),
    ("US", "USA", 840, "United States", "USD", "$", "1"),
    ("UY", "URY", 858, "Uruguay", "UYU", "$", "598"),
    ("UZ", "UZB", 860, "Uzbekistan", "UZS", "so'm", "998"),
    ("VU", "VUT", 548, "Vanuatu", "VUV", "Vt", "678"),
    ("VA", "VAT", 336, "Vatican City", "EUR", "€", "379"),
    ("VE", "VEN", 862, "Venezuela", "VES", "Bs.", "58"),
    ("VN", "VNM", 704, "Vietnam", "VND", "₫", "84"),
    ("YE", "YEM", 887, "Yemen", "YER", "﷼", "967"),
    ("ZM", "ZMB", 894, "Zambia", "ZMW", "ZK", "260"),
    ("ZW", "ZWE", 716, "Zimbabwe", "ZWL", "$", "263"),
]
